<template>
<div class="space-y-6">
  <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-wider text-blue-600">Marketing</p><h1 class="mt-1 text-3xl font-black">Google Search</h1><p class="mt-1 text-slate-500">Search Console performance and SEO opportunities for the shop.</p></div><div class="flex gap-2"><select v-model="days" class="input" @change="load"><option :value="7">Last 7 days</option><option :value="28">Last 28 days</option><option :value="30">Last 30 days</option><option :value="90">Last 90 days</option></select><button class="btn-secondary" @click="load">Refresh</button></div></div>
  <div v-if="error" class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{{error}}</div>
  <div v-if="loading" class="rounded-2xl border bg-white p-8 text-center text-slate-500">Loading Google Search Console…</div>
  <template v-else-if="data">
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Search Impressions" :value="num(data.summary.impressions)" :change="data.summary.change.impressions"/><Stat label="Search Clicks" :value="num(data.summary.clicks)" :change="data.summary.change.clicks"/><Stat label="CTR" :value="`${data.summary.ctr.toFixed(2)}%`" :change="data.summary.change.ctr"/><Stat label="Average Position" :value="data.summary.position.toFixed(1)" :position-change="data.summary.change.position"/></div>
    <div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><b>Search Console property:</b> {{data.site_url}} <span class="text-blue-700">• {{data.start_date}} to {{data.end_date}}</span></div>
    <div class="grid gap-6 xl:grid-cols-2"><DataTable title="Top Search Queries" kind="query" :rows="filteredQueries" v-model:search="querySearch"/><DataTable title="Top Landing Pages" kind="page" :rows="filteredPages" v-model:search="pageSearch"/></div>
    <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="text-lg font-black">Search Opportunities</h2><p class="mt-1 text-sm text-slate-500">Signals worth reviewing rather than automatic SEO problems.</p><div class="mt-4 grid gap-4 lg:grid-cols-3"><Opportunity title="High impressions, low CTR" :rows="data.opportunities.high_impressions_low_ctr" kind="query"/><Opportunity title="Close to page one" :rows="data.opportunities.near_page_one" kind="query"/><Opportunity title="Landing pages with low CTR" :rows="data.opportunities.pages_high_impressions_low_ctr" kind="page"/></div></section>
    <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Indexing:</b> this page intentionally reports Search Analytics only. Search Console's performance API does not provide a complete site-wide count of every indexed/not-indexed URL, so we won't manufacture one.</div>
  </template>
</div>
</template>
<script setup lang="ts">
definePageMeta({layout:"admin",middleware:["admin"]});
const {adminFetch}=useAdminFetch(); const data=ref<any>(null),error=ref(""),loading=ref(false),days=ref(28),querySearch=ref(""),pageSearch=ref("");
const num=(v:any)=>Number(v||0).toLocaleString("en-AU");
async function load(){loading.value=true;error.value="";try{data.value=await adminFetch(`/api/admin/google-search?days=${days.value}`)}catch(e:any){error.value=e?.data?.statusMessage||e?.data?.message||e?.statusMessage||e?.message||"Unable to load Google Search Console."}finally{loading.value=false}}
onMounted(load);
const filteredQueries=computed(()=>{const q=querySearch.value.toLowerCase();return (data.value?.queries||[]).filter((x:any)=>!q||x.query.toLowerCase().includes(q)).slice(0,250)});
const filteredPages=computed(()=>{const q=pageSearch.value.toLowerCase();return (data.value?.pages||[]).filter((x:any)=>!q||x.page.toLowerCase().includes(q)).slice(0,250)});
const Stat=defineComponent({props:{label:String,value:[String,Number],change:Number,positionChange:Number},setup(p){return()=>h("div",{class:"rounded-2xl border border-slate-200 bg-white p-5"},[h("div",{class:"text-3xl font-black"},String(p.value??0)),h("div",{class:"mt-1 text-sm font-bold text-slate-500"},p.label),p.change!==undefined&&p.change!==null?h("div",{class:`mt-2 text-xs font-bold ${p.change>=0?'text-green-700':'text-red-700'}`},`${p.change>=0?'+':''}${p.change.toFixed(1)}% vs previous period`):p.positionChange!==undefined&&p.positionChange!==null?h("div",{class:`mt-2 text-xs font-bold ${p.positionChange<=0?'text-green-700':'text-red-700'}`},`${p.positionChange>0?'+':''}${p.positionChange.toFixed(1)} positions vs previous`):null])}});
const DataTable=defineComponent({props:{title:String,kind:String,rows:Array,search:String},emits:["update:search"],setup(p,{emit}){return()=>h("section",{class:"rounded-2xl border border-slate-200 bg-white overflow-hidden"},[h("div",{class:"border-b p-4"},[h("h2",{class:"font-black text-lg"},p.title),h("input",{class:"input mt-3 w-full",value:p.search,placeholder:"Search…",onInput:(e:any)=>emit("update:search",e.target.value)})]),h("div",{class:"overflow-x-auto max-h-[560px]"},[h("table",{class:"w-full min-w-[620px] text-sm"},[h("thead",{class:"sticky top-0 bg-slate-50 text-xs uppercase text-slate-500"},h("tr",{},[h("th",{class:"p-3 text-left"},p.kind==='query'?'Query':'Page'),h("th",{class:"p-3 text-right"},"Impressions"),h("th",{class:"p-3 text-right"},"Clicks"),h("th",{class:"p-3 text-right"},"CTR"),h("th",{class:"p-3 text-right"},"Position")])),h("tbody",{},(p.rows as any[]||[]).map((r:any)=>h("tr",{class:"border-t"},[h("td",{class:"p-3 font-semibold break-all"},r[p.kind as string]),h("td",{class:"p-3 text-right"},num(r.impressions)),h("td",{class:"p-3 text-right"},num(r.clicks)),h("td",{class:"p-3 text-right"},`${r.ctr.toFixed(2)}%`),h("td",{class:"p-3 text-right"},r.position.toFixed(1))]))])])])}});
const Opportunity=defineComponent({props:{title:String,rows:Array,kind:String},setup(p){return()=>h("div",{class:"rounded-xl border bg-slate-50 p-4"},[h("h3",{class:"font-black"},p.title),...(p.rows as any[]||[]).slice(0,8).map((r:any)=>h("div",{class:"mt-3 border-t pt-3 text-xs"},[h("div",{class:"font-bold break-all"},r[p.kind as string]),h("div",{class:"mt-1 text-slate-500"},`${num(r.impressions)} impressions • ${r.ctr.toFixed(2)}% CTR • position ${r.position.toFixed(1)}`)])),!(p.rows as any[]||[]).length?h("p",{class:"mt-3 text-xs text-slate-500"},"Nothing flagged in this period."):null])}});
</script>
