<template>
  <div class="space-y-6">
    <div class="flex flex-wrap items-end justify-between gap-4">
      <div>
        <p class="text-xs font-black uppercase tracking-wider text-violet-600">Search Visibility</p>
        <h1 class="mt-1 text-3xl font-black text-slate-900">SEO Health Centre</h1>
        <p class="mt-1 max-w-3xl text-slate-500">Find catalogue and category pages that need search-data, content or identifier improvements.</p>
      </div>
      <button class="btn-secondary" :disabled="loading" @click="load">{{ loading ? "Checking…" : "Refresh Health" }}</button>
    </div>

    <div v-if="error" class="rounded-xl border border-red-200 bg-red-50 p-4 font-semibold text-red-700">{{ error }}</div>

    <template v-if="data">
      <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <Stat label="Products Healthy" :value="`${data.summary.healthy_products} / ${data.summary.active_products}`" />
        <Stat label="Products Need Attention" :value="data.summary.products_with_issues" />
        <Stat label="Categories Healthy" :value="`${data.summary.healthy_categories} / ${data.summary.active_categories}`" />
        <Stat label="Categories Need Attention" :value="data.summary.categories_with_issues" />
      </div>

      <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        <button class="health-chip" @click="showProductIssue('auto_title')"><strong>{{ data.summary.automatic_titles }}</strong><span>Automatic product titles</span></button>
        <button class="health-chip" @click="showProductIssue('auto_meta')"><strong>{{ data.summary.automatic_meta }}</strong><span>Automatic product meta</span></button>
        <button class="health-chip" @click="showProductIssue('missing_image')"><strong>{{ data.summary.missing_image }}</strong><span>Missing images</span></button>
        <button class="health-chip" @click="showProductIssue('missing_identifier')"><strong>{{ data.summary.missing_identifiers }}</strong><span>Identifier issues</span></button>
        <button class="health-chip" @click="showCategoryIssue('missing_content')"><strong>{{ data.summary.categories_missing_content }}</strong><span>Categories missing content</span></button>
      </div>

      <div class="grid gap-4 lg:grid-cols-3">
        <section class="card p-5">
          <h2 class="text-lg font-black">Search Discovery</h2>
          <p class="mt-1 text-sm text-slate-500">Public discovery files generated by the store.</p>
          <div class="mt-4 space-y-2">
            <a :href="data.endpoints.sitemap" target="_blank" class="seo-link">Sitemap.xml →</a>
            <a :href="data.endpoints.robots" target="_blank" class="seo-link">Robots.txt →</a>
          </div>
        </section>
        <section class="card p-5">
          <h2 class="text-lg font-black">Google Merchant</h2>
          <p class="mt-1 text-sm text-slate-500">Live shopping feed generated from active products.</p>
          <a :href="data.endpoints.merchant" target="_blank" class="seo-link mt-4">Merchant Feed →</a>
        </section>
        <section class="card p-5">
          <h2 class="text-lg font-black">SEO Stage 3</h2>
          <p class="mt-1 text-sm leading-6 text-slate-500">Custom product/category search fields, canonical URLs, category content, sitemap and breadcrumb structured data are enabled.</p>
          <div class="mt-4 text-sm font-bold text-green-700">✓ Health checks use your custom SEO fields</div>
        </section>
      </div>

      <section class="card overflow-hidden">
        <div class="border-b border-slate-200 p-4 sm:p-5">
          <div class="flex flex-wrap items-center gap-2">
            <button class="tab-btn" :class="tab==='products'?'tab-active':''" @click="tab='products';issueFilter='all'">Products <span>{{ data.summary.active_products }}</span></button>
            <button class="tab-btn" :class="tab==='categories'?'tab-active':''" @click="tab='categories';issueFilter='all'">Categories <span>{{ data.summary.active_categories }}</span></button>
          </div>
          <div class="mt-4 flex flex-col gap-3 lg:flex-row lg:items-center">
            <input v-model="search" class="input flex-1" :placeholder="tab==='products'?'Search product, SKU, brand or category…':'Search category…'" />
            <select v-model="issueFilter" class="input lg:max-w-xs">
              <option v-for="f in currentFilters" :key="f[0]" :value="f[0]">{{ f[1] }}</option>
            </select>
            <select v-model="healthFilter" class="input lg:max-w-[190px]">
              <option value="attention">Needs attention</option>
              <option value="all">All</option>
              <option value="healthy">Healthy only</option>
            </select>
          </div>
        </div>

        <div v-if="tab==='products'" class="overflow-x-auto">
          <table class="w-full min-w-[1050px] text-left text-sm">
            <thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">Product / SKU</th><th class="px-4 py-3">Health</th><th class="px-4 py-3">Issues</th><th class="px-4 py-3">Search Preview</th><th class="px-4 py-3"></th></tr></thead>
            <tbody>
              <tr v-for="p in filteredProducts" :key="p.id" class="border-t border-slate-200 align-top">
                <td class="px-4 py-4"><div class="font-black text-slate-900">{{ p.name }}</div><div class="mt-1 text-xs text-slate-500"><strong>SKU:</strong> {{ p.product_code || "Missing" }} · {{ p.category || "No category" }}</div><div v-if="p.brand" class="mt-1 text-xs text-slate-400">{{ p.brand }}</div></td>
                <td class="px-4 py-4"><HealthBadge :score="p.score" :issues="p.issues" /></td>
                <td class="px-4 py-4"><IssueList :issues="p.issues" /></td>
                <td class="px-4 py-4"><div class="max-w-md"><div class="truncate text-base font-medium text-[#1a0dab]">{{ p.seo_title }}</div><div class="truncate text-xs text-green-700">{{ productUrl(p) }}</div><div class="mt-1 line-clamp-2 text-xs leading-5 text-slate-600">{{ p.seo_description }}</div></div></td>
                <td class="px-4 py-4 whitespace-nowrap"><NuxtLink :to="productEditLink(p)" class="font-bold text-blue-600">Fix Product →</NuxtLink></td>
              </tr>
              <tr v-if="!filteredProducts.length"><td colspan="5" class="px-5 py-12 text-center text-slate-500">No products match these health filters.</td></tr>
            </tbody>
          </table>
        </div>

        <div v-else class="overflow-x-auto">
          <table class="w-full min-w-[1000px] text-left text-sm">
            <thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">Category</th><th class="px-4 py-3">Products</th><th class="px-4 py-3">Health</th><th class="px-4 py-3">Issues</th><th class="px-4 py-3">Search Preview</th><th class="px-4 py-3"></th></tr></thead>
            <tbody>
              <tr v-for="c in filteredCategories" :key="c.id" class="border-t border-slate-200 align-top">
                <td class="px-4 py-4"><div class="font-black text-slate-900">{{ c.name }}</div><div class="mt-1 text-xs text-slate-500">/{{ c.slug || "missing-slug" }}</div></td>
                <td class="px-4 py-4 font-bold text-slate-700">{{ c.product_count }}</td>
                <td class="px-4 py-4"><HealthBadge :score="c.score" :issues="c.issues" /></td>
                <td class="px-4 py-4"><IssueList :issues="c.issues" /></td>
                <td class="px-4 py-4"><div class="max-w-md"><div class="truncate text-base font-medium text-[#1a0dab]">{{ c.seo_title }}</div><div class="truncate text-xs text-green-700">{{ categoryUrl(c) }}</div><div class="mt-1 line-clamp-2 text-xs leading-5 text-slate-600">{{ c.seo_description }}</div></div></td>
                <td class="px-4 py-4 whitespace-nowrap"><NuxtLink :to="`/admin/categories/${c.id}`" class="font-bold text-blue-600">Fix Category →</NuxtLink></td>
              </tr>
              <tr v-if="!filteredCategories.length"><td colspan="6" class="px-5 py-12 text-center text-slate-500">No categories match these health filters.</td></tr>
            </tbody>
          </table>
        </div>
      </section>

      <p class="text-xs text-slate-400">Last checked {{ formatChecked(data.generated_at) }}. Automatic title/meta warnings are recommendations to review, not errors; the storefront still has working fallbacks.</p>
    </template>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: "admin", middleware: ["admin"] });
const { adminFetch, isSuperAdmin } = useAdminFetch();
const router = useRouter();
const loading=ref(true), error=ref(""), data=ref<any>(null), search=ref(""), tab=ref<"products"|"categories">("products"), issueFilter=ref("all"), healthFilter=ref("attention");

onMounted(async()=>{ if(!isSuperAdmin.value){ await router.replace("/admin"); return; } await load(); });
async function load(){ loading.value=true;error.value="";try{data.value=await adminFetch("/api/admin/marketing-seo")}catch(e:any){error.value=e?.data?.statusMessage||e?.message||"Unable to load SEO health."}finally{loading.value=false} }

const currentFilters=computed(()=>data.value?.issue_filters?.[tab.value]||[["all","All issues"]]);
const issueMatches=(row:any)=>{
  if(issueFilter.value==="all") return true;
  if(issueFilter.value==="errors") return row.issues.some((i:any)=>i.severity==="error");
  return row.issues.some((i:any)=>i.key===issueFilter.value);
};
const healthMatches=(row:any)=>healthFilter.value==="all" ? true : healthFilter.value==="healthy" ? !row.issues.length : row.issues.length>0;
const filteredProducts=computed(()=>{
  const q=search.value.trim().toLowerCase();
  return [...(data.value?.products||[])].filter((p:any)=>healthMatches(p)&&issueMatches(p)&&(!q||`${p.name} ${p.product_code||""} ${p.category||""} ${p.brand||""}`.toLowerCase().includes(q))).sort((a:any,b:any)=>a.score-b.score||String(a.name).localeCompare(String(b.name)));
});
const filteredCategories=computed(()=>{
  const q=search.value.trim().toLowerCase();
  return [...(data.value?.categories||[])].filter((c:any)=>healthMatches(c)&&issueMatches(c)&&(!q||`${c.name} ${c.slug||""}`.toLowerCase().includes(q))).sort((a:any,b:any)=>a.score-b.score||String(a.name).localeCompare(String(b.name)));
});

function showProductIssue(key:string){tab.value="products";issueFilter.value=key;healthFilter.value="attention";}
function showCategoryIssue(key:string){tab.value="categories";issueFilter.value=key;healthFilter.value="attention";}
const productUrl=(p:any)=>`${data.value?.endpoints?.base||""}/product/${p.slug||""}`;
const categoryUrl=(c:any)=>`${data.value?.endpoints?.base||""}/category/${c.slug||""}`;
const productEditLink=(p:any)=>p.issues.some((i:any)=>i.key==="variant_identifier")?`/admin/products/${p.id}/variants`:`/admin/products/${p.id}`;
const formatChecked=(v:string)=>new Intl.DateTimeFormat("en-AU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));

const Stat=defineComponent({props:{label:String,value:[String,Number]},setup(props){return()=>h("div",{class:"card p-5"},[h("div",{class:"text-3xl font-black text-slate-900"},String(props.value??0)),h("div",{class:"mt-1 text-sm font-bold text-slate-500"},props.label)])}});
const HealthBadge=defineComponent({props:{score:Number,issues:Array},setup(props){return()=>h("span",{class:["rounded-full px-2.5 py-1 text-xs font-black",!props.issues?.length?"bg-green-100 text-green-700":(props.issues as any[]).some(x=>x.severity==="error")?"bg-red-100 text-red-700":"bg-amber-100 text-amber-800"]},!props.issues?.length?"Healthy":`${props.score??0}%`) }});
const IssueList=defineComponent({props:{issues:Array},setup(props){return()=>!props.issues?.length?h("span",{class:"font-bold text-green-700"},"✓ Healthy"):h("div",{class:"flex max-w-md flex-wrap gap-1.5"},(props.issues as any[]).map((i:any)=>h("span",{class:["rounded px-2 py-1 text-xs font-semibold",i.severity==="error"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-800"]},i.label))) }});
</script>

<style scoped>
.card{border:1px solid #e2e8f0;border-radius:1rem;background:white;box-shadow:0 1px 2px rgb(15 23 42 / .04)}
.seo-link{display:block;border:1px solid #dbeafe;border-radius:.75rem;background:#eff6ff;padding:.7rem .85rem;font-weight:800;color:#1d4ed8}.seo-link:hover{background:#dbeafe}
.health-chip{display:flex;min-height:78px;align-items:center;gap:.8rem;border:1px solid #e2e8f0;border-radius:1rem;background:white;padding:1rem;text-align:left;box-shadow:0 1px 2px rgb(15 23 42 / .04);transition:.15s}.health-chip:hover{border-color:#c4b5fd;background:#faf5ff}.health-chip strong{font-size:1.5rem;color:#0f172a}.health-chip span{font-size:.78rem;font-weight:800;color:#64748b}
.tab-btn{display:inline-flex;align-items:center;gap:.5rem;border-radius:.75rem;padding:.6rem .9rem;font-size:.875rem;font-weight:800;color:#64748b}.tab-btn span{border-radius:999px;background:#f1f5f9;padding:.1rem .45rem;font-size:.7rem}.tab-active{background:#eef2ff;color:#4338ca}.tab-active span{background:#fff}
</style>
