<template><main class="admin-page"><div class="admin-page-inner max-w-6xl">
  <div class="mb-8"><p class="text-sm font-bold uppercase tracking-wide text-violet-600">Administration</p><h1 class="mt-1 text-3xl font-black text-slate-900">Security Groups</h1><p class="mt-2 text-slate-500">Create admin access groups and choose which areas each group can use. SuperAdmins always retain full access. Existing ungrouped Admin accounts keep their current full access.</p></div>
  <div v-if="message" class="mb-5 rounded-xl border border-green-200 bg-green-50 p-4 text-green-700">{{message}}</div><div v-if="error" class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{{error}}</div>
  <section class="mb-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="text-xl font-black">{{editId?'Edit':'Create'}} Security Group</h2><p class="text-sm text-slate-500">Access is enforced by the server API as well as hidden from the menu.</p></div><button v-if="editId" class="admin-btn-secondary" @click="resetForm">Cancel</button></div>
    <div class="mt-5 grid gap-4 md:grid-cols-2"><label><span class="text-sm font-bold">Group Name</span><input v-model="form.name" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" placeholder="e.g. Sales Team" /></label><label><span class="text-sm font-bold">Description</span><input v-model="form.description" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" placeholder="What this group is for" /></label></div>
    <div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label v-for="s in sections" :key="s.key" class="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4"><input v-model="form.permissions[s.key]" type="checkbox" class="mt-1 h-4 w-4"/><span><strong class="block">{{s.label}}</strong><small class="text-slate-500">{{s.help}}</small></span></label></div>
    <button class="admin-btn-primary mt-5" :disabled="saving" @click="saveGroup">{{saving?'Saving...':editId?'Save Group':'Create Group'}}</button>
  </section>
  <section class="mb-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Groups</h2><div class="mt-4 grid gap-4 lg:grid-cols-2"><div v-for="g in groups" :key="g.id" class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between gap-3"><div><h3 class="font-black">{{g.name}}</h3><p class="text-sm text-slate-500">{{g.description||'No description'}}</p></div><div class="flex gap-2"><button class="admin-btn-secondary" @click="edit(g)">Edit</button><button class="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-600" @click="remove(g)">Delete</button></div></div><div class="mt-3 flex flex-wrap gap-2"><span v-for="s in sections" :key="s.key" class="rounded-full px-2.5 py-1 text-xs font-bold" :class="g.permissions?.[s.key]?'bg-green-100 text-green-700':'bg-slate-100 text-slate-400'">{{s.label}} {{g.permissions?.[s.key]?'✓':'—'}}</span></div></div><p v-if="!groups.length" class="text-slate-500">No security groups yet.</p></div></section>
  <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Administrator Access</h2><p class="mt-1 text-sm text-slate-500">Assign Admin accounts to a group. “Legacy Full Access” preserves the access they had before security groups were introduced.</p><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b"><th class="p-3">Administrator</th><th class="p-3">Role</th><th class="p-3">Security Group</th></tr></thead><tbody><tr v-for="a in admins" :key="a.id" class="border-b border-slate-100"><td class="p-3 font-semibold">{{a.email}}</td><td class="p-3">{{a.role}}</td><td class="p-3"><span v-if="a.role==='superadmin'" class="font-bold text-violet-700">Full Access (SuperAdmin)</span><select v-else :value="a.security_group_id||''" class="min-w-56 rounded-lg border border-slate-300 px-3 py-2" @change="assign(a,($event.target as HTMLSelectElement).value)"><option value="">Legacy Full Access</option><option v-for="g in groups" :key="g.id" :value="g.id">{{g.name}}</option></select></td></tr></tbody></table></div></section>
</div></main></template>
<script setup lang="ts">
definePageMeta({layout:'admin',middleware:['admin','superadmin']}); const {adminFetch}=useAdminFetch();
const sections=[{key:'product',label:'Product',help:'Products, categories, stock and reviews'},{key:'sales',label:'Sales',help:'Orders, quotes and customers'},{key:'purchase',label:'Purchase',help:'Suppliers, POs, receiving and stock intelligence'},{key:'accounting',label:'Accounting',help:'Ledgers, invoices, reconciliation and financial reports'},{key:'administration',label:'Administration',help:'Admin tools, chat and system administration'},{key:'business',label:'Business',help:'Freight, pricing, marketing, analytics and store operations'}];
const groups=ref<any[]>([]),admins=ref<any[]>([]),saving=ref(false),editId=ref<string|null>(null),message=ref(''),error=ref('');
const blank=()=>({name:'',description:'',permissions:Object.fromEntries(sections.map(s=>[s.key,false]))}); const form=reactive<any>(blank());
const load=async()=>{try{const r:any=await adminFetch('/api/admin/security-groups');groups.value=r.groups||[];admins.value=r.admins||[]}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Unable to load security groups.'}};
const resetForm=()=>{editId.value=null;Object.assign(form,blank())}; const edit=(g:any)=>{editId.value=g.id;form.name=g.name;form.description=g.description||'';form.permissions={...blank().permissions,...g.permissions};window.scrollTo({top:0,behavior:'smooth'})};
const saveGroup=async()=>{saving.value=true;error.value='';message.value='';try{await adminFetch(editId.value?`/api/admin/security-groups/${editId.value}`:'/api/admin/security-groups',{method:editId.value?'PUT':'POST',body:form});message.value='Security group saved.';resetForm();await load()}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Unable to save group.'}finally{saving.value=false}};
const remove=async(g:any)=>{if(!confirm(`Delete security group “${g.name}”?`))return;try{await adminFetch(`/api/admin/security-groups/${g.id}`,{method:'DELETE'});message.value='Security group deleted.';await load()}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Unable to delete group.'}};
const assign=async(a:any,id:string)=>{try{await adminFetch('/api/admin/security-groups/assign',{method:'PUT',body:{user_id:a.id,security_group_id:id||null}});message.value=`Access updated for ${a.email}.`;await load()}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Unable to assign group.';await load()}};
onMounted(load);
</script>
