<template>
<section id="reviews" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7 scroll-mt-24">
 <div class="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[.14em] text-cyan-600">Customer feedback</p><h2 class="mt-1 text-2xl font-black text-slate-900">Product Reviews</h2></div><div v-if="data.count" class="flex items-center gap-3"><span class="text-3xl font-black">{{ data.average }}</span><div><div class="text-xl text-amber-400">{{ stars(data.average) }}</div><div class="text-xs text-slate-500">{{ data.count }} review{{ data.count===1?'':'s' }}</div></div></div></div>
 <div v-if="customerUser" class="mt-5"><div v-if="eligibility?.eligible" class="rounded-xl border border-blue-100 bg-blue-50/50 p-4"><h3 class="font-black text-slate-900">{{ eligibility.existing ? 'Update your review' : 'Write a review' }}</h3><div class="mt-3 flex gap-1"><button v-for="n in 5" :key="n" type="button" class="text-3xl" :class="n<=form.rating?'text-amber-400':'text-slate-300'" @click="form.rating=n">★</button></div><input v-model="form.title" maxlength="120" placeholder="Review title (optional)" class="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2"><textarea v-model="form.review" maxlength="3000" rows="4" placeholder="Tell other customers what you think..." class="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2"></textarea><div class="mt-3 flex items-center gap-3"><button :disabled="busy" class="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white disabled:opacity-50" @click="submit">{{ busy?'Submitting…':'Submit Review' }}</button><span v-if="message" class="text-sm font-semibold" :class="error?'text-red-600':'text-green-700'">{{ message }}</span></div><p class="mt-2 text-xs text-slate-500">Verified purchase. Reviews are checked before appearing publicly.</p></div><p v-else-if="eligibility && !eligibility.existing" class="text-sm text-slate-500">You can review this product after a delivered purchase.</p></div>
 <div v-else class="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><NuxtLink :to="`/auth/signin?redirect=${encodeURIComponent(route.fullPath+'#reviews')}`" class="font-bold text-blue-600">Sign in</NuxtLink> to write a verified-purchase review.</div>
 <div v-if="!data.count" class="py-10 text-center text-slate-500">No approved reviews yet. Be the first verified purchaser to leave one.</div>
 <div v-else class="mt-6 space-y-5"><article v-for="r in data.reviews" :key="r.id" class="border-b border-slate-100 pb-5 last:border-0"><div class="flex flex-wrap items-center gap-2"><span class="text-amber-400">{{ stars(r.rating) }}</span><strong>{{ r.title || 'Customer review' }}</strong><span v-if="r.verified_purchase" class="rounded-full bg-emerald-50 px-2 py-0.5 text-[11px] font-bold text-emerald-700">✓ Verified Purchase</span></div><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-700">{{ r.review }}</p><p class="mt-2 text-xs text-slate-400">{{ formatDate(r.created_at) }}</p></article></div>
</section></template>
<script setup lang="ts">
const props=defineProps<{productId:number|string}>(); const supabase=useSupabaseClient(); const customerUser=useSupabaseUser(); const route=useRoute();
const data=ref<any>({average:0,count:0,distribution:[],reviews:[]}), eligibility=ref<any>(null), busy=ref(false),message=ref(''),error=ref(false),form=reactive({rating:5,title:'',review:''});
const stars=(v:number)=>{const n=Math.round(Number(v||0));return '★'.repeat(n)+'☆'.repeat(5-n)}; const formatDate=(v:string)=>new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v));
async function authHeaders(){const {data:{session}}=await supabase.auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}}
async function load(){data.value=await $fetch(`/api/reviews/${props.productId}`); if(customerUser.value){try{eligibility.value=await $fetch(`/api/reviews/${props.productId}/eligibility`,{headers:await authHeaders()});if(eligibility.value?.existing){Object.assign(form,{rating:eligibility.value.existing.rating,title:eligibility.value.existing.title||'',review:eligibility.value.existing.review||''})}}catch{eligibility.value=null}}}
async function submit(){busy.value=true;message.value='';error.value=false;try{const r:any=await $fetch(`/api/reviews/${props.productId}`,{method:'POST',headers:await authHeaders(),body:form});message.value=r.message;await load()}catch(e:any){error.value=true;message.value=e?.data?.statusMessage||e?.message||'Unable to submit review.'}finally{busy.value=false}}
onMounted(load); watch(()=>customerUser.value?.id,load);
</script>
