<template><NuxtPage v-if="route.path.endsWith('/print')"/><main v-else class="admin-core-page mx-auto max-w-[1500px] px-4 py-6 md:px-7 md:py-7">
<AdminPurchasingWorkflow/><div class="flex flex-wrap items-center justify-between gap-3"><div><NuxtLink to="/admin/purchasing/purchase-orders" class="text-sm font-bold text-blue-600">← Purchase Orders</NuxtLink><h1 class="mt-2 text-3xl font-black">{{po?.po_number||'Purchase Order'}}</h1><p class="text-slate-500">Supplier order management, receiving, billing and payment status.</p></div><span v-if="po" class="rounded-full px-3 py-1 text-sm font-black" :class="statusClass(po.status)">{{label(po.status)}}</span></div>
<div v-if="msg" class="my-4 rounded-xl bg-slate-100 p-3 text-sm">{{msg}}</div><div v-if="loading" class="panel mt-5 p-6">Loading purchase order…</div>
<template v-else-if="po">
<section class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div class="metric"><small>Supplier</small><b>{{po.accounting_suppliers?.name||'—'}}</b></div><div class="metric"><small>Order Total</small><b>{{money(po.total)}}</b></div><div class="metric"><small>Ordered</small><b>{{qtyTotal}}</b></div><div class="metric"><small>Received</small><b>{{receivedTotal}}</b></div><div class="metric"><small>Outstanding</small><b>{{outstandingTotal}}</b></div></section>
<section class="panel mt-5 p-5"><div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="text-xl font-black">Order Management</h2><p class="text-sm text-slate-500">Manage the supplier order and move it through purchasing.</p></div><div class="flex flex-wrap gap-2"><NuxtLink :to="`/admin/purchasing/purchase-orders/${po.id}/print`" target="_blank" class="secondary">Print / PDF</NuxtLink><NuxtLink v-if="isDraft" :to="`/admin/purchasing/purchase-orders/new?edit=${po.id}`" class="secondary">Edit Draft</NuxtLink><button v-if="isDraft" class="primary" @click="send">Email PO to Supplier</button><button v-if="isDraft" class="secondary" @click="markOrdered">Mark Ordered</button><button class="secondary" @click="duplicate">Duplicate PO</button><button v-if="isDraft" class="danger" @click="cancel">Cancel PO</button></div></div>
<div class="mt-5 grid gap-4 md:grid-cols-2"><div><h3 class="font-black">Supplier</h3><p class="mt-2 font-bold">{{po.accounting_suppliers?.name}}</p><p class="text-sm text-slate-600">{{po.accounting_suppliers?.contact_name||''}}</p><p class="text-sm text-slate-600">{{po.accounting_suppliers?.email||'No supplier email'}}</p><p class="text-sm text-slate-600">{{po.accounting_suppliers?.phone||''}}</p></div><div><h3 class="font-black">Order Details</h3><div class="mt-2 grid gap-2 sm:grid-cols-2"><label class="text-xs font-bold text-slate-500">Expected delivery<input v-model="edit.expected_date" type="date" class="input mt-1"></label><label class="text-xs font-bold text-slate-500">Supplier confirmation / reference<input v-model="edit.supplier_reference" class="input mt-1" placeholder="Supplier order number"></label></div><label class="mt-2 block text-xs font-bold text-slate-500">Notes<textarea v-model="edit.notes" rows="2" class="input mt-1"></textarea></label><button class="secondary mt-2" @click="saveDetails">Save Order Details</button></div></div></section>
<section class="panel mt-5 p-5"><h2 class="text-xl font-black">Order Lines</h2><div class="mt-3 overflow-x-auto"><table class="w-full min-w-[850px] text-sm"><thead><tr class="border-b text-left"><th class="p-2">SKU</th><th>Product</th><th class="text-right">Ordered</th><th class="text-right">Received</th><th class="text-right">Outstanding</th><th class="text-right">Unit ex GST</th><th class="text-right">Total</th></tr></thead><tbody><tr v-for="l in po.accounting_purchase_order_lines||[]" :key="l.id" class="border-b"><td class="p-2">{{l.sku||'—'}}</td><td class="font-bold">{{l.description}}</td><td class="text-right">{{num(l.quantity)}}</td><td class="text-right text-emerald-700">{{num(l.received_quantity)}}</td><td class="text-right" :class="Number(l.remaining_quantity)>0?'font-black text-amber-700':''">{{num(l.remaining_quantity)}}</td><td class="text-right">{{money(l.unit_cost_ex_gst)}}</td><td class="text-right font-bold">{{money(Number(l.quantity)*Number(l.unit_cost_ex_gst)*1.1)}}</td></tr></tbody></table></div><div class="mt-4 flex justify-end gap-2"><NuxtLink v-if="canReceive&&outstandingTotal>0" to="/admin/purchasing/purchase-orders/receive-stock" class="primary">Receive Stock</NuxtLink><button v-if="canBill" class="secondary" @click="createBill">Create Supplier Bill</button></div></section>
<section class="mt-5 grid gap-5 lg:grid-cols-2"><div class="panel p-5"><h2 class="text-xl font-black">Receiving History</h2><div v-if="!po.receipts?.length" class="mt-3 text-sm text-slate-500">No stock receipts yet.</div><div v-for="r in po.receipts||[]" :key="r.id" class="mt-3 rounded-xl border border-slate-200 p-3"><div class="flex justify-between gap-3"><b>Receipt #{{r.id}}</b><span>{{date(r.received_date)}}</span></div><p class="mt-1 text-sm">Reference: {{r.supplier_reference||'—'}}</p><p v-if="r.notes" class="text-sm text-slate-500">{{r.notes}}</p></div></div>
<div class="panel p-5"><h2 class="text-xl font-black">Bill & Payment</h2><div v-if="!po.bill" class="mt-3 text-sm text-slate-500">No supplier bill has been created yet.</div><template v-else><div class="mt-3 flex items-center justify-between"><div><b>{{po.bill.bill_number}}</b><p class="text-sm text-slate-500">Supplier invoice: {{po.bill.supplier_invoice_number||'—'}}</p></div><span class="badge">{{label(po.bill.status)}}</span></div><div class="mt-3 grid grid-cols-3 gap-2 text-sm"><div><small>Total</small><b class="block">{{money(po.bill.total)}}</b></div><div><small>Paid</small><b class="block">{{money(po.bill.paid_amount)}}</b></div><div><small>Owing</small><b class="block">{{money(Math.max(0,Number(po.bill.total)-Number(po.bill.paid_amount)))}}</b></div></div><NuxtLink to="/admin/accounting/payables" class="secondary mt-3 inline-block">Open Accounts Payable</NuxtLink><div v-if="po.payments?.length" class="mt-4 border-t pt-3"><b class="text-sm">Payment History</b><div v-for="p in po.payments" :key="p.id" class="mt-2 flex justify-between text-sm"><span>{{date(p.payment_date||p.created_at)}} · {{p.reference||'Payment'}}</span><b>{{money(p.amount)}}</b></div></div></template></div></section>
<section class="panel mt-5 p-5"><h2 class="text-xl font-black">Activity</h2><div class="mt-4 space-y-3"><div v-for="a in activity" :key="a.key" class="flex gap-3"><div class="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-blue-500"></div><div><b class="text-sm">{{a.title}}</b><p class="text-xs text-slate-500">{{a.when}}</p></div></div></div></section>
</template></main></template>
<script setup lang="ts">
definePageMeta({layout:'admin',middleware:['admin']}); const route=useRoute(),router=useRouter(),dialog=useAppDialog(),{adminFetch}=useAdminFetch(); const po=ref<any>(null),loading=ref(true),msg=ref(''); const edit=reactive<any>({expected_date:'',supplier_reference:'',notes:''});
const money=(v:any)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v||0)),num=(v:any)=>new Intl.NumberFormat('en-AU',{maximumFractionDigits:2}).format(Number(v||0)),date=(v:any)=>v?new Intl.DateTimeFormat('en-AU',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)): '—',label=(v:any)=>String(v||'draft').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const isDraft=computed(()=>String(po.value?.status||'').toLowerCase()==='draft'),canReceive=computed(()=>['sent','ordered','part_received'].includes(String(po.value?.status||'').toLowerCase())),canBill=computed(()=>!po.value?.bill&&!['draft','closed'].includes(String(po.value?.status||'').toLowerCase())); const qtyTotal=computed(()=>sum('quantity')),receivedTotal=computed(()=>sum('received_quantity')),outstandingTotal=computed(()=>sum('remaining_quantity')); function sum(k:string){return (po.value?.accounting_purchase_order_lines||[]).reduce((s:number,x:any)=>s+Number(x[k]||0),0)} function statusClass(v:any){const s=String(v||'').toLowerCase();return s==='paid'?'bg-emerald-100 text-emerald-800':s==='closed'?'bg-slate-200 text-slate-700':s.includes('received')?'bg-teal-100 text-teal-800':s==='draft'?'bg-amber-100 text-amber-800':'bg-blue-100 text-blue-800'}
async function load(){loading.value=true;try{po.value=await adminFetch(`/api/admin/accounting/purchase-orders/${route.params.id}`);Object.assign(edit,{expected_date:po.value.expected_date||'',supplier_reference:po.value.supplier_reference||'',notes:po.value.notes||''})}catch(e:any){msg.value=e?.data?.statusMessage||e.message}finally{loading.value=false}}
async function saveDetails(){try{await adminFetch(`/api/admin/accounting/purchase-orders/${po.value.id}/details`,{method:'PATCH',body:edit});msg.value='Purchase order details saved.';await load()}catch(e:any){msg.value=e?.data?.statusMessage||e.message}}
async function send(){if(!await dialog.confirm(`Email ${po.value.po_number} to ${po.value.accounting_suppliers?.email||'the supplier'}?`))return;try{const x:any=await adminFetch(`/api/admin/accounting/purchase-orders/${po.value.id}/send`,{method:'POST'});msg.value=`Purchase order emailed to ${x.email_sent_to}.`;await load()}catch(e:any){msg.value=e?.data?.statusMessage||e.message}}
async function markOrdered(){if(!await dialog.confirm('Mark this purchase order as ordered without sending an email?'))return;try{await adminFetch(`/api/admin/accounting/purchase-orders/${po.value.id}/mark-ordered`,{method:'POST'});msg.value='Purchase order marked as ordered.';await load()}catch(e:any){msg.value=e?.data?.statusMessage||e.message}}
async function cancel(){if(!await dialog.confirm('Cancel/close this draft purchase order?'))return;try{await adminFetch(`/api/admin/accounting/purchase-orders/${po.value.id}/close`,{method:'POST'});msg.value='Purchase order cancelled.';await load()}catch(e:any){msg.value=e?.data?.statusMessage||e.message}}
async function duplicate(){if(!await dialog.confirm('Create a new draft purchase order using these same lines?'))return;try{const x:any=await adminFetch(`/api/admin/accounting/purchase-orders/${po.value.id}/duplicate`,{method:'POST'});await router.push(`/admin/purchasing/purchase-orders/${x.id}`)}catch(e:any){msg.value=e?.data?.statusMessage||e.message}}
async function createBill(){const inv=await dialog.prompt('Supplier invoice number',po.value.supplier_reference||'');if(inv===null)return;const due=await dialog.prompt('Due date (YYYY-MM-DD)','')||null;try{await adminFetch(`/api/admin/accounting/purchase-orders/${po.value.id}/bill`,{method:'POST',body:{supplier_invoice_number:inv,due_date:due}});msg.value='Supplier bill created.';await load()}catch(e:any){msg.value=e?.data?.statusMessage||e.message}}
const activity=computed(()=>{const a:any[]=[];if(po.value?.created_at)a.push({key:'created',title:'Purchase order created',when:date(po.value.created_at)});if(['sent','ordered','part_received','received','billed','paid'].includes(String(po.value?.status||'').toLowerCase()))a.push({key:'ordered',title:String(po.value.status).toLowerCase()==='sent'?'Purchase order sent to supplier':'Purchase order progressed to ordering',when:date(po.value.updated_at||po.value.order_date)});for(const r of po.value?.receipts||[])a.push({key:`r${r.id}`,title:`Stock received${r.supplier_reference?' · '+r.supplier_reference:''}`,when:date(r.received_date)});if(po.value?.bill)a.push({key:'bill',title:`Supplier bill ${po.value.bill.bill_number} created`,when:date(po.value.bill.created_at||po.value.bill.bill_date)});for(const p of po.value?.payments||[])a.push({key:`p${p.id}`,title:`Supplier payment ${money(p.amount)} recorded`,when:date(p.payment_date||p.created_at)});return a}); onMounted(load)
</script>
<style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.metric{@apply rounded-xl border border-slate-200 bg-white p-4 shadow-sm}.metric small{@apply block text-xs font-bold uppercase tracking-wide text-slate-500}.metric b{@apply mt-1 block text-lg}.input{@apply w-full rounded-lg border border-slate-300 px-3 py-2 text-sm font-normal text-slate-900}.primary{@apply rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white}.secondary{@apply rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-bold}.danger{@apply rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-sm font-bold text-red-700}.badge{@apply rounded-full bg-blue-100 px-2 py-1 text-xs font-black uppercase text-blue-700}</style>
