<template>
<main class="admin-content">
  <NuxtLink to="/admin/purchasing" class="text-sm font-bold text-blue-600">← Purchasing</NuxtLink>
  <div class="mt-2 flex flex-wrap items-end justify-between gap-4">
    <div><p class="text-xs font-black uppercase tracking-wider text-blue-600">SuperAdmin</p><h1 class="text-3xl font-black">Inventory & COGS</h1><p class="text-slate-500">Stock control, valuation, movements and cost of goods sold.</p></div>
    <div class="flex flex-wrap gap-2"><label><span class="label">From</span><input v-model="start" type="date" class="input"></label><label><span class="label">To</span><input v-model="end" type="date" class="input"></label><button class="btn-primary" @click="load">Run Report</button></div>
  </div>
  <div v-if="err" class="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{{err}}</div>

  <div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">
    <div class="panel p-5"><small>Inventory Value</small><div class="metric">{{money(data.summary?.inventory_value)}}</div></div>
    <div class="panel p-5"><small>Retail Value</small><div class="metric">{{money(data.summary?.retail_value)}}</div></div>
    <div class="panel p-5"><small>Units on Hand</small><div class="metric">{{num(data.summary?.units_on_hand)}}</div></div>
    <div class="panel p-5"><small>COGS for Period</small><div class="metric">{{money(data.summary?.period_cogs)}}</div></div>
    <div class="panel p-5"><small>Low / No Stock</small><div class="metric">{{num(data.summary?.low_stock_products)}}</div></div>
    <div class="panel p-5"><small>Potential Margin</small><div class="metric">{{money(data.summary?.potential_margin)}}</div></div>
  </div>

  <section class="panel mt-5 overflow-hidden">
    <div class="flex flex-wrap items-end justify-between gap-3 p-5"><div><h2 class="text-xl font-black">Stock Control</h2><p class="text-sm text-slate-500">Current stock, cost, value and stock health. Click a product to inspect its movement history.</p></div><div class="flex flex-wrap gap-2"><input v-model="search" class="input" placeholder="Search product or SKU…"><select v-model="stockFilter" class="input"><option value="all">All stock</option><option value="available">In stock</option><option value="low">Low stock (1–5)</option><option value="out">Out / backorder</option></select></div></div>
    <div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">Product</th><th>SKU</th><th>Status</th><th class="text-right">Stock</th><th class="text-right">Unit Cost</th><th class="text-right">Inventory Value</th><th class="text-right">Retail Value</th><th class="text-right pr-3">Potential Margin</th></tr></thead><tbody>
      <tr v-for="x in filteredValuation" :key="x.id" class="cursor-pointer border-t hover:bg-blue-50" @click="selectedProductId=selectedProductId===x.id?0:x.id"><td class="p-3 font-bold"><span class="mr-2 text-slate-400">{{selectedProductId===x.id?'▾':'›'}}</span>{{x.name}}</td><td>{{x.sku||'—'}}</td><td><span :class="statusClass(x.stock)" class="rounded-full px-2 py-1 text-xs font-black">{{stockStatus(x.stock)}}</span></td><td class="text-right font-bold">{{num(x.stock)}}</td><td class="text-right">{{money(x.unit_cost)}}</td><td class="text-right font-bold">{{money(x.value)}}</td><td class="text-right">{{money(x.retail_value)}}</td><td class="text-right pr-3">{{money(x.potential_margin)}}</td></tr>
      <tr v-if="!filteredValuation.length"><td colspan="8" class="p-8 text-center text-slate-500">No products match this filter.</td></tr>
    </tbody></table></div>
  </section>

  <section v-if="selectedProduct" class="panel mt-5 overflow-hidden">
    <div class="flex flex-wrap items-start justify-between gap-3 p-5"><div><p class="text-xs font-black uppercase tracking-wide text-blue-600">Product movement history</p><h2 class="text-xl font-black">{{selectedProduct.name}}</h2><p class="text-sm text-slate-500">{{selectedProduct.sku||'No SKU'}} · {{num(selectedProduct.stock)}} currently on hand · {{money(selectedProduct.unit_cost)}} current unit cost</p></div><button class="btn-secondary" @click="selectedProductId=0">Close</button></div>
    <div class="grid gap-3 border-y bg-slate-50 p-4 sm:grid-cols-4"><div><small>Received / In</small><div class="font-black">{{num(selectedStats.qtyIn)}} units</div></div><div><small>Sold / Out</small><div class="font-black">{{num(selectedStats.qtyOut)}} units</div></div><div><small>Cost In</small><div class="font-black">{{money(selectedStats.costIn)}}</div></div><div><small>COGS / Cost Out</small><div class="font-black">{{money(selectedStats.costOut)}}</div></div></div>
    <div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">Date</th><th>Movement</th><th>Reference</th><th class="text-right">Qty</th><th class="text-right">Unit Cost</th><th class="text-right pr-3">Total Cost</th></tr></thead><tbody><tr v-for="x in selectedMovements" :key="x.id" class="border-t"><td class="p-3">{{x.movement_date}}</td><td class="font-bold">{{movementLabel(x.movement_type)}}</td><td>{{x.reference||sourceLabel(x)||'—'}}</td><td class="text-right" :class="Number(x.quantity)<0?'text-red-600':'text-emerald-700'">{{Number(x.quantity)>0?'+':''}}{{num(x.quantity)}}</td><td class="text-right">{{money(x.unit_cost_ex_gst)}}</td><td class="text-right pr-3">{{money(Math.abs(Number(x.total_cost_ex_gst||0)))}}</td></tr><tr v-if="!selectedMovements.length"><td colspan="6" class="p-6 text-center text-slate-500">No movements for this product in the selected period.</td></tr></tbody></table></div>
  </section>

  <section class="panel mt-5 p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-xl font-black">Manual Stock Adjustment</h2><p class="text-sm text-slate-500">Record damaged stock, corrections, found stock or other audited adjustments.</p></div><NuxtLink to="/admin/purchasing/purchase-orders/receive-stock" class="btn-secondary">Receive Purchase Orders →</NuxtLink></div><div class="mt-4 grid gap-3 md:grid-cols-3"><select v-model.number="adjust.product_id" class="input"><option :value="0">Choose product…</option><option v-for="x in data.valuation" :key="x.id" :value="x.id">{{x.name}} ({{num(x.stock)}} on hand)</option></select><select v-model="adjust.direction" class="input"><option value="in">Increase stock</option><option value="out">Decrease stock</option></select><input v-model.number="adjust.quantity" type="number" min="0.001" step="1" class="input" placeholder="Quantity"><input v-model.number="adjust.unit_cost" type="number" min="0" step=".01" class="input" placeholder="Unit cost ex GST"><input v-model="adjust.reference" class="input" placeholder="Reference / reason"><input v-model="adjust.movement_date" type="date" class="input"></div><textarea v-model="adjust.notes" class="input mt-3 w-full" rows="2" placeholder="Notes (optional)"></textarea><div class="mt-3 flex justify-end"><button class="btn-primary" :disabled="saving" @click="saveAdjustment">{{saving?'Posting…':'Post Adjustment'}}</button></div></section>

  <section class="panel mt-5 overflow-hidden"><div class="p-5"><h2 class="text-xl font-black">COGS by Product</h2><p class="text-sm text-slate-500">Historical cost captured when sales are posted to accounting.</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">Product</th><th>SKU</th><th class="text-right">Qty Sold</th><th class="text-right pr-3">COGS</th></tr></thead><tbody><tr v-for="x in data.profitability" :key="x.product_id" class="border-t"><td class="p-3 font-bold">{{x.name}}</td><td>{{x.sku||'—'}}</td><td class="text-right">{{num(x.quantity_sold)}}</td><td class="text-right pr-3 font-bold">{{money(x.cogs)}}</td></tr><tr v-if="!data.profitability?.length"><td colspan="4" class="p-6 text-center text-slate-500">No COGS movements in this period yet.</td></tr></tbody></table></div></section>

  <section class="panel mt-5 overflow-hidden"><div class="flex flex-wrap items-end justify-between gap-3 p-5"><div><h2 class="text-xl font-black">Complete Stock Movement Ledger</h2><p class="text-sm text-slate-500">Purchases, sales and adjustments for the selected period.</p></div><select v-model="movementFilter" class="input"><option value="all">All movements</option><option value="in">Stock in</option><option value="out">Stock out</option><option value="sale">Sales / COGS</option><option value="adjustment">Adjustments</option></select></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">Date</th><th>Product</th><th>Type</th><th>Reference</th><th class="text-right">Qty</th><th class="text-right pr-3">Cost</th></tr></thead><tbody><tr v-for="x in filteredMovements" :key="x.id" class="border-t"><td class="p-3">{{x.movement_date}}</td><td class="font-bold">{{x.products?.name||x.product_id}}</td><td>{{movementLabel(x.movement_type)}}</td><td>{{x.reference||sourceLabel(x)||'—'}}</td><td class="text-right" :class="Number(x.quantity)<0?'text-red-600':'text-emerald-700'">{{Number(x.quantity)>0?'+':''}}{{num(x.quantity)}}</td><td class="text-right pr-3">{{money(Math.abs(Number(x.total_cost_ex_gst||0)))}}</td></tr><tr v-if="!filteredMovements.length"><td colspan="6" class="p-6 text-center text-slate-500">No movements match this filter.</td></tr></tbody></table></div></section>
</main>
</template>
<script setup lang="ts">
definePageMeta({layout:"admin",middleware:["admin"]});
const{adminFetch,isSuperAdmin}=useAdminFetch();const now=new Date(),fy=now.getMonth()>=6?now.getFullYear():now.getFullYear()-1;const start=ref(`${fy}-07-01`),end=ref(`${fy+1}-06-30`),err=ref(""),saving=ref(false),search=ref(""),stockFilter=ref("all"),movementFilter=ref("all"),selectedProductId=ref<any>(0);const data=reactive<any>({summary:{},valuation:[],profitability:[],movements:[]}),adjust=reactive<any>({product_id:0,direction:"out",quantity:1,unit_cost:null,reference:"",notes:"",movement_date:new Date().toISOString().slice(0,10)});
const money=(v:any)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v||0));const num=(v:any)=>new Intl.NumberFormat("en-AU",{maximumFractionDigits:3}).format(Number(v||0));
const filteredValuation=computed(()=>data.valuation.filter((x:any)=>{const q=search.value.trim().toLowerCase(),match=!q||String(x.name||"").toLowerCase().includes(q)||String(x.sku||"").toLowerCase().includes(q),s=Number(x.stock||0);return match&&(stockFilter.value==="all"||(stockFilter.value==="available"&&s>5)||(stockFilter.value==="low"&&s>0&&s<=5)||(stockFilter.value==="out"&&s<=0))}));
const filteredMovements=computed(()=>data.movements.filter((x:any)=>movementFilter.value==="all"||(movementFilter.value==="in"&&Number(x.quantity)>0)||(movementFilter.value==="out"&&Number(x.quantity)<0)||(movementFilter.value==="sale"&&x.movement_type==="sale")||(movementFilter.value==="adjustment"&&String(x.movement_type).startsWith("adjustment"))));
const selectedProduct=computed(()=>data.valuation.find((x:any)=>String(x.id)===String(selectedProductId.value)));const selectedMovements=computed(()=>data.movements.filter((x:any)=>String(x.product_id)===String(selectedProductId.value)));const selectedStats=computed(()=>selectedMovements.value.reduce((a:any,x:any)=>{const q=Number(x.quantity||0),c=Math.abs(Number(x.total_cost_ex_gst||0));if(q>0){a.qtyIn+=q;a.costIn+=c}else{a.qtyOut+=Math.abs(q);a.costOut+=c}return a},{qtyIn:0,qtyOut:0,costIn:0,costOut:0}));
const stockStatus=(v:any)=>Number(v)<=0?'Out / Backorder':Number(v)<=5?'Low Stock':'In Stock';const statusClass=(v:any)=>Number(v)<=0?'bg-red-100 text-red-700':Number(v)<=5?'bg-amber-100 text-amber-800':'bg-emerald-100 text-emerald-700';const movementLabel=(v:any)=>({sale:'Sale / COGS',purchase_receipt:'Purchase Receipt',receipt:'Purchase Receipt',adjustment_in:'Adjustment In',adjustment_out:'Adjustment Out'} as any)[String(v)]||String(v||'Movement').replaceAll('_',' ').replace(/\b\w/g,(m)=>m.toUpperCase());const sourceLabel=(x:any)=>x.source_type?`${x.source_type} ${x.source_id||''}`:'';
async function load(){err.value="";try{if(!isSuperAdmin.value)return navigateTo("/admin");Object.assign(data,await adminFetch(`/api/admin/accounting/inventory/report?start=${start.value}&end=${end.value}`))}catch(e:any){err.value=e?.data?.statusMessage||e.message}}
async function saveAdjustment(){err.value="";saving.value=true;try{await adminFetch("/api/admin/accounting/inventory/adjust",{method:"POST",body:adjust});Object.assign(adjust,{product_id:0,direction:"out",quantity:1,unit_cost:null,reference:"",notes:"",movement_date:new Date().toISOString().slice(0,10)});await load()}catch(e:any){err.value=e?.data?.statusMessage||e.message}finally{saving.value=false}}
onMounted(load)
</script>
<style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.metric{@apply mt-1 text-2xl font-black}.label{@apply mb-1 block text-xs font-bold text-slate-600}.input{@apply rounded-lg border border-slate-300 px-3 py-2}.btn-primary{@apply self-end rounded-lg bg-blue-600 px-5 py-2.5 font-bold text-white disabled:opacity-50}.btn-secondary{@apply rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-bold}</style>
