import { getAdminSupabase, requireAdmin } from "~~/server/utils/adminAuth";
import { getStandardPricingLevel } from "~~/server/utils/customerPricing";
import { localiseProductImages } from "~~/server/utils/productImageLocaliser";
const slug=(v:any)=>String(v||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
const money=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;
async function categoryId(s:any,parentName:string,childName:string){
  async function ensure(name:string,parent_id:number|null){let q=s.from("categories").select("id,name,parent_id").ilike("name",name).limit(10);const {data,error}=await q;if(error)throw new Error(error.message);const found=(data||[]).find((x:any)=>Number(x.parent_id||0)===Number(parent_id||0));if(found)return Number(found.id);const {data:made,error:e}=await s.from("categories").insert({name,slug:slug(name),parent_id,active:true}).select("id").single();if(e)throw new Error(e.message);return Number(made.id)}
  const parent=await ensure(parentName,null);return childName&&childName!==parentName?await ensure(childName,parent):parent;
}
export default defineEventHandler(async(event)=>{
  await requireAdmin(event);const b=await readBody(event),r=b?.product||{},supplierId=Number(b?.supplier_id);if(!supplierId)throw createError({statusCode:400,statusMessage:"Leader supplier is required."});if(!r.supplier_sku||!r.name)throw createError({statusCode:400,statusMessage:"Invalid Leader product."});
  const s=getAdminSupabase(),catId=await categoryId(s,String(r.leader_category||"Leader Products"),String(r.leader_subcategory||"Uncategorised"));
  const states=r.stock_by_state||{},stockFields={leader_stock_vic:Math.max(0,Number(states.VIC||0)),leader_stock_nsw:Math.max(0,Number(states.NSW||0)),leader_stock_qld:Math.max(0,Number(states.QLD||0)),leader_stock_sa:Math.max(0,Number(states.SA||0)),leader_stock_wa:Math.max(0,Number(states.WA||0)),leader_stock_updated_at:new Date().toISOString()};
  let existingId=Number(r.existing_product_id||0);if(!existingId){const {data:x}=await s.from("products").select("id").ilike("product_code",String(r.supplier_sku)).limit(1).maybeSingle();existingId=Number(x?.id||0)}
  if(existingId){const {error}=await s.from("products").update({category_id:catId,...stockFields}).eq("id",existingId);if(error)throw createError({statusCode:500,statusMessage:error.message});const {data:link}=await s.from("accounting_product_suppliers").select("id").eq("product_id",existingId).eq("supplier_id",supplierId).maybeSingle();if(link?.id)await s.from("accounting_product_suppliers").update({supplier_sku:r.supplier_sku,buy_price_ex_gst:Number(r.buy_price_ex_gst||0),is_primary:true,updated_at:new Date().toISOString()}).eq("id",link.id);else await s.from("accounting_product_suppliers").insert({product_id:existingId,supplier_id:supplierId,supplier_sku:r.supplier_sku,buy_price_ex_gst:Number(r.buy_price_ex_gst||0),is_primary:true});return {ok:true,action:"moved",product_id:existingId,category_id:catId};}
  const level=await getStandardPricingLevel(),buy=Number(r.buy_price_ex_gst||0),sellMarkup=Number(level.markupPercent||0),rrpInc=Number(r.rrp_inc_gst||0),rrpEx=rrpInc>0?rrpInc/1.1:buy*(1+Math.max(sellMarkup+20,30)/100),rrpMarkup=buy>0?Math.max(0,((rrpEx-buy)/buy)*100):0;const local=await localiseProductImages(Array.isArray(r.images)?r.images:[],String(r.supplier_sku));const sellEx=buy*(1+sellMarkup/100);const desc=String(r.description||"").trim();const seoTitle=String(r.name).slice(0,60),seoDescription=(desc||String(r.name)).replace(/\s+/g," ").slice(0,160);
  const payload:any={name:r.name,slug:slug(r.supplier_sku),product_code:r.supplier_sku,brand:r.brand||null,gtin:r.gtin||null,mpn:r.mpn||null,seo_title:seoTitle,seo_description:seoDescription,has_variants:false,blurb:desc.slice(0,400)||null,description:desc?[{type:"paragraph",text:desc}]:[],buy_price_ex_gst:money(buy),sell_markup_percent:sellMarkup,pricing_level_markup_override_percent:0,rrp_markup_percent:money(rrpMarkup),price:Math.max(1,Math.round(sellEx*1.1)),oldPrice:Math.max(1,Math.round(rrpEx*1.1)),stock:0,low_stock_level:2,reorder_level:3,target_stock_level:5,weight_kg:1,length_cm:Math.max(1,Number(r.box_length_mm||300)/10),width_cm:Math.max(1,Number(r.box_width_mm||200)/10),height_cm:Math.max(1,Number(r.box_height_mm||100)/10),active:true,featured:false,refurbished:false,images:local.images,category_id:catId,...stockFields};
  const {data,error}=await s.from("products").insert(payload).select("id").single();if(error)throw createError({statusCode:500,statusMessage:error.message});const {error:se}=await s.from("accounting_product_suppliers").insert({product_id:data.id,supplier_id:supplierId,supplier_sku:r.supplier_sku,buy_price_ex_gst:money(buy),is_primary:true});if(se)throw createError({statusCode:500,statusMessage:se.message});return {ok:true,action:"created",product_id:data.id,category_id:catId};
});
