<template><main class="admin-content">
<div class="flex flex-wrap items-end justify-between gap-4"><div><NuxtLink to="/admin/products" class="text-sm font-bold text-blue-600">← Products</NuxtLink><p class="mt-3 text-xs font-black uppercase tracking-wider text-blue-600">Products</p><h1 class="text-3xl font-black">Product Data Health</h1><p class="text-slate-500">Find incomplete product records before they affect purchasing, stocktake or accounting.</p></div><button class="btn-secondary" @click="load">Refresh Check</button></div>
<div v-if="err" class="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 font-semibold text-red-700">{{err}}</div>
<section class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div class="metric"><small>Products</small><b>{{summary.total}}</b></div><div class="metric"><small>Healthy</small><b class="text-emerald-700">{{summary.healthy}}</b></div><div class="metric"><small>Warnings</small><b class="text-amber-700">{{summary.warning}}</b></div><div class="metric"><small>Critical</small><b class="text-red-700">{{summary.critical}}</b></div><div class="metric"><small>Total Issues</small><b>{{summary.issues}}</b></div></section>
<section class="panel mt-5 p-4"><div class="grid gap-3 lg:grid-cols-[1fr_220px_220px]"><input v-model="search" class="input" placeholder="Search product or SKU…"><select v-model="status" class="input"><option value="issues">Products with issues</option><option value="all">All products</option><option value="critical">Critical only</option><option value="warning">Warnings only</option><option value="healthy">Healthy only</option></select><select v-model="issue" class="input"><option value="">All issue types</option><option v-for="x in issueTypes" :key="x.key" :value="x.key">{{x.label}}</option></select></div></section>
<section class="panel mt-5 overflow-hidden"><div v-if="loading" class="p-10 text-center text-slate-500">Checking products…</div><div v-else class="overflow-x-auto"><table class="w-full min-w-[1050px] text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">Product</th><th>SKU</th><th>Supplier</th><th>Supplier SKU</th><th class="text-right">Buy</th><th class="text-center">Levels L/R/T</th><th>Issues</th><th class="pr-3">Action</th></tr></thead><tbody>
<tr v-for="p in filtered" :key="p.id" class="border-t"><td class="p-3"><div class="font-bold">{{p.name}}</div><span class="text-xs" :class="p.active?'text-emerald-700':'text-slate-400'">{{p.active?'Active':'Inactive'}}</span></td><td>{{p.sku||'—'}}</td><td>{{p.primary_supplier||'—'}}</td><td>{{p.supplier_sku||'—'}}</td><td class="text-right">{{money(p.buy_price)}}</td><td class="text-center font-bold">{{p.low_stock_level}} / {{p.reorder_level}} / {{p.target_stock_level}}</td><td><div class="flex max-w-[380px] flex-wrap gap-1"><span v-if="!p.issues.length" class="pill good">Healthy</span><span v-for="x in p.issues" :key="x.key+x.label" class="pill" :class="x.severity==='critical'?'bad':'warn'">{{x.label}}</span></div></td><td class="pr-3"><NuxtLink :to="`/admin/products/${p.id}`" class="font-bold text-blue-600">Edit Product</NuxtLink></td></tr>
<tr v-if="!filtered.length"><td colspan="8" class="p-10 text-center text-slate-500">No products match the selected health filters.</td></tr></tbody></table></div></section>
</main></template>
<script setup lang="ts">definePageMeta({layout:"admin",middleware:["admin"]});const{adminFetch}=useAdminFetch();const loading=ref(true),err=ref(""),search=ref(""),status=ref("issues"),issue=ref(""),products=ref<any[]>([]),summary=ref<any>({total:0,healthy:0,warning:0,critical:0,issues:0});const money=(v:any)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v||0));const issueTypes=computed(()=>{const m=new Map();for(const p of products.value)for(const x of p.issues)m.set(x.key,{key:x.key,label:x.label});return[...m.values()].sort((a:any,b:any)=>a.label.localeCompare(b.label))});const filtered=computed(()=>{const q=search.value.toLowerCase().trim();return products.value.filter((p:any)=>{if(q&&!p.name.toLowerCase().includes(q)&&!String(p.sku||"").toLowerCase().includes(q))return false;if(status.value==="issues"&&!p.issues.length)return false;if(["critical","warning","healthy"].includes(status.value)&&p.health!==status.value)return false;if(issue.value&&!p.issues.some((x:any)=>x.key===issue.value))return false;return true})});async function load(){loading.value=true;err.value="";try{const r:any=await adminFetch("/api/admin/products/data-health");products.value=r.products||[];summary.value=r.summary||summary.value}catch(e:any){err.value=e?.data?.statusMessage||e?.message||"Unable to check product data."}finally{loading.value=false}}onMounted(load)</script>
<style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.metric{@apply rounded-xl border border-slate-200 bg-white p-4 shadow-sm}.metric small{@apply block text-xs font-bold uppercase text-slate-500}.metric b{@apply mt-1 block text-2xl}.input{@apply rounded-lg border border-slate-300 bg-white px-3 py-2 outline-none focus:border-blue-500}.btn-secondary{@apply rounded-lg border border-slate-300 bg-white px-4 py-2 font-bold hover:bg-slate-50}.pill{@apply rounded-full px-2 py-1 text-xs font-bold}.good{@apply bg-emerald-100 text-emerald-700}.warn{@apply bg-amber-100 text-amber-800}.bad{@apply bg-red-100 text-red-700}</style>