<template><main class="admin-content">
<div class="flex flex-wrap items-end justify-between gap-4"><div><NuxtLink to="/admin/products" class="text-sm font-bold text-blue-600">← Products</NuxtLink><p class="mt-3 text-xs font-black uppercase tracking-wider text-blue-600">Products</p><h1 class="text-3xl font-black">Inventory Control</h1><p class="text-slate-500">On hand, allocated, available stock and landed inventory value.</p></div><button class="btn-secondary" @click="load">Refresh</button></div>
<div v-if="err" class="mt-4 rounded-xl bg-red-50 p-3 font-semibold text-red-700">{{err}}</div>
<section class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="metric"><small>On Hand</small><b>{{summary.onHand}}</b></div><div class="metric"><small>Allocated</small><b>{{summary.allocated}}</b></div><div class="metric"><small>Available</small><b>{{summary.available}}</b></div><div class="metric"><small>Landed Stock Value</small><b>{{money(summary.value)}}</b></div></section>
<section class="panel mt-5 p-4"><input v-model="search" class="input w-full" placeholder="Search product, variant, SKU or category…"></section>
<section class="panel mt-5 overflow-hidden"><div v-if="loading" class="p-10 text-center text-slate-500">Loading inventory…</div><div v-else class="overflow-x-auto"><table class="w-full min-w-[1050px] text-sm"><thead><tr class="bg-slate-50 text-left text-xs uppercase text-slate-500"><th class="p-3">Product</th><th>SKU</th><th>Category</th><th class="text-right">On Hand</th><th class="text-right">Allocated</th><th class="text-right">Available</th><th class="text-right">Supplier Cost</th><th class="text-right">Landed Cost</th><th class="p-3 text-right">Stock Value</th></tr></thead><tbody><tr v-for="x in shown" :key="x.key" class="border-t"><td class="p-3"><b>{{x.product_name}}</b><div v-if="x.variant_name" class="text-xs text-slate-500">{{x.variant_name}}</div></td><td>{{x.code||'—'}}</td><td>{{x.category}}</td><td class="text-right font-bold">{{x.stock}}</td><td class="text-right">{{x.allocated||0}}</td><td class="text-right" :class="Number(x.available)<=0?'font-bold text-red-600':''">{{x.available}}</td><td class="text-right">{{money(x.buy_price_ex_gst)}}</td><td class="text-right">{{money(x.landed_cost_ex_gst)}}</td><td class="p-3 text-right font-bold">{{money(x.stock_value_ex_gst)}}</td></tr></tbody></table></div></section>
</main></template>
<script setup lang="ts">definePageMeta({layout:'admin',middleware:['admin']});const{adminFetch}=useAdminFetch();const loading=ref(true),err=ref(''),search=ref(''),items=ref<any[]>([]);const money=(v:any)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v||0));const shown=computed(()=>{const q=search.value.toLowerCase().trim();return items.value.filter((x:any)=>!q||[x.product_name,x.variant_name,x.code,x.category].some(v=>String(v||'').toLowerCase().includes(q)))});const summary=computed(()=>({onHand:items.value.reduce((a,x)=>a+Number(x.stock||0),0),allocated:items.value.reduce((a,x)=>a+Number(x.allocated||0),0),available:items.value.reduce((a,x)=>a+Number(x.available||0),0),value:items.value.reduce((a,x)=>a+Number(x.stock_value_ex_gst||0),0)}));async function load(){loading.value=true;err.value='';try{const r:any=await adminFetch('/api/admin/inventory');items.value=r.items||[]}catch(e:any){err.value=e?.data?.statusMessage||e?.message||'Unable to load inventory.'}finally{loading.value=false}}onMounted(load)</script>
<style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.metric{@apply rounded-xl border border-slate-200 bg-white p-5 shadow-sm}.metric small{@apply block text-xs font-bold uppercase text-slate-500}.metric b{@apply mt-1 block text-2xl}.input{@apply rounded-lg border border-slate-300 bg-white px-3 py-2}.btn-secondary{@apply rounded-lg border border-slate-300 bg-white px-4 py-2 font-bold text-slate-700 hover:bg-slate-50}</style>
