<template><main class="admin-content">
<div class="flex flex-wrap items-end justify-between gap-4"><div><NuxtLink to="/admin/products" class="text-sm font-bold text-blue-600">← Products</NuxtLink><p class="mt-3 text-xs font-black uppercase tracking-wider text-blue-600">Products</p><h1 class="text-3xl font-black">Reorder Centre</h1><p class="text-slate-500">Products at or below reorder level, grouped by primary supplier.</p></div><NuxtLink to="/admin/purchasing/purchase-orders/new" class="btn-primary">New Purchase Order</NuxtLink></div>
<div v-if="err" class="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 font-semibold text-red-700">{{err}}</div>
<section class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div class="metric"><small>Products to reorder</small><b>{{reorderRows.length}}</b></div><div class="metric"><small>Suggested units</small><b>{{units}}</b></div><div class="metric"><small>Suggested purchase</small><b>{{money(cost)}}</b></div><div class="metric"><small>Suppliers</small><b>{{groups.length}}</b></div></section>
<section class="panel mt-5 p-4"><div class="grid gap-3 md:grid-cols-[1fr_240px]"><input v-model="search" class="input" placeholder="Search product, SKU or supplier…"><select v-model="supplierFilter" class="input"><option value="">All suppliers</option><option value="none">No supplier</option><option v-for="g in groups.filter(x=>x.supplier_id)" :key="g.key" :value="String(g.supplier_id)">{{g.name}}</option></select></div></section>
<div v-if="loading" class="panel mt-5 p-10 text-center">Calculating reorder requirements…</div>
<section v-for="g in visibleGroups" :key="g.key" class="panel mt-5 overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 class="text-xl font-black">{{g.name}}</h2><p class="text-sm text-slate-500">{{g.rows.length}} products · {{g.rows.reduce((a:any,x:any)=>a+x.suggested_order,0)}} units · {{money(g.rows.reduce((a:any,x:any)=>a+x.suggested_cost,0))}}</p></div><NuxtLink v-if="g.supplier_id" :to="`/admin/purchasing/suppliers/${g.supplier_id}/purchase-order-preview`" class="btn-primary">Generate PO Preview</NuxtLink><span v-else class="rounded-lg bg-red-100 px-3 py-2 text-sm font-bold text-red-700">Assign a primary supplier first</span></div>
<div class="overflow-x-auto"><table class="w-full min-w-[950px] text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">Product</th><th>SKU</th><th>Supplier SKU</th><th class="text-right">Stock</th><th class="text-right">On Order</th><th class="text-right">Reorder</th><th class="text-right">Target</th><th class="text-right">Suggested</th><th class="text-right pr-3">Cost</th></tr></thead><tbody><tr v-for="p in g.rows" :key="p.id" class="border-t"><td class="p-3 font-bold">{{p.name}}</td><td>{{p.sku||'—'}}</td><td>{{p.supplier_sku||'—'}}</td><td class="text-right">{{p.stock}}</td><td class="text-right">{{p.on_order}}</td><td class="text-right">{{p.reorder_level}}</td><td class="text-right">{{p.target_stock}}</td><td class="text-right font-black text-blue-700">{{p.suggested_order}}</td><td class="text-right pr-3 font-bold">{{money(p.suggested_cost)}}</td></tr></tbody></table></div></section>
<div v-if="!loading&&!visibleGroups.length" class="panel mt-5 p-10 text-center text-slate-500">Nothing currently needs reordering for this filter.</div>
</main></template>
<script setup lang="ts">
definePageMeta({layout:"admin",middleware:["admin"]});const{adminFetch,isSuperAdmin}=useAdminFetch();const loading=ref(true),err=ref(""),rows=ref<any[]>([]),search=ref(""),supplierFilter=ref("");const money=(v:any)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v||0));const reorderRows=computed(()=>rows.value.filter((x:any)=>Number(x.suggested_order)>0));const units=computed(()=>reorderRows.value.reduce((a:number,x:any)=>a+Number(x.suggested_order||0),0));const cost=computed(()=>reorderRows.value.reduce((a:number,x:any)=>a+Number(x.suggested_cost||0),0));const groups=computed(()=>{const m=new Map<string,any>();for(const p of reorderRows.value){const key=p.supplier_id?String(p.supplier_id):"none";if(!m.has(key))m.set(key,{key,supplier_id:p.supplier_id,name:p.supplier_name||"No Primary Supplier",rows:[]});m.get(key).rows.push(p)}return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name))});const visibleGroups=computed(()=>{const q=search.value.trim().toLowerCase();return groups.value.map((g:any)=>({...g,rows:g.rows.filter((p:any)=>(!supplierFilter.value||String(p.supplier_id||"none")===supplierFilter.value)&&(!q||`${p.name} ${p.sku||""} ${p.supplier_sku||""} ${g.name}`.toLowerCase().includes(q)))})).filter((g:any)=>g.rows.length)});async function load(){loading.value=true;err.value="";try{if(!isSuperAdmin.value)return navigateTo("/admin");const r:any=await adminFetch("/api/admin/accounting/stock-intelligence");rows.value=r.products||[]}catch(e:any){err.value=e?.data?.statusMessage||e?.message||"Unable to load reorder information."}finally{loading.value=false}}onMounted(load);
</script><style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.input{@apply rounded-lg border border-slate-300 bg-white px-3 py-2}.metric{@apply rounded-xl border border-slate-200 bg-white p-4 shadow-sm}.metric small{@apply block text-xs font-bold uppercase tracking-wide text-slate-500}.metric b{@apply mt-1 block text-2xl font-black}.btn-primary{@apply inline-flex rounded-lg bg-blue-600 px-4 py-2 font-bold text-white hover:bg-blue-700}</style>