<template><main class="admin-content">
<div class="flex flex-wrap items-end justify-between gap-4"><div><NuxtLink to="/admin/products" class="text-sm font-bold text-blue-600">← Products</NuxtLink><p class="mt-3 text-xs font-black uppercase tracking-wider text-blue-600">Products</p><h1 class="text-3xl font-black">Reorder Centre</h1><p class="text-slate-500">Select products, adjust quantities and create one draft purchase order per supplier.</p></div><NuxtLink to="/admin/purchasing/purchase-orders" class="btn-secondary">Purchase Orders</NuxtLink></div>
<div v-if="err" class="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 font-semibold text-red-700">{{err}}</div>
<div v-if="message" class="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 font-semibold text-emerald-700">{{message}}</div>
<section class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div class="metric"><small>Products to Reorder</small><b>{{reorderRows.length}}</b></div><div class="metric"><small>Selected Products</small><b>{{selectedRows.length}}</b></div><div class="metric"><small>Selected Units</small><b>{{selectedUnits}}</b></div><div class="metric"><small>Selected Cost ex GST</small><b>{{money(selectedCost)}}</b></div></section>
<section class="panel mt-5 p-4"><div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><input v-model="search" class="input w-full lg:max-w-xl" placeholder="Search product, SKU or supplier…"><div class="flex flex-wrap gap-2"><button class="btn-secondary" @click="selectAllShown">Select Visible</button><button class="btn-secondary" @click="clearSelection">Clear Selection</button><button class="btn-primary" :disabled="!selectedRows.length||creating" @click="reviewOpen=true">{{creating?'Creating…':`Generate ${selectedSupplierCount} Draft PO${selectedSupplierCount===1?'':'s'}`}}</button></div></div></section>
<div v-if="loading" class="panel mt-5 p-10 text-center text-slate-500">Checking reorder levels…</div>
<section v-for="g in groups" :key="g.key" class="panel mt-5 overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b bg-slate-50 p-4"><div class="flex items-center gap-3"><input type="checkbox" class="h-5 w-5" :checked="groupSelected(g)" @change="toggleGroup(g)"><div><h2 class="text-xl font-black">{{g.name}}</h2><p class="text-sm text-slate-500">{{g.rows.length}} product{{g.rows.length===1?'':'s'}} requiring reorder</p></div></div><span v-if="!g.supplier_id" class="rounded-lg bg-red-100 px-3 py-2 text-sm font-bold text-red-700">Primary supplier required</span></div>
<div class="overflow-x-auto"><table class="w-full min-w-[1050px] text-sm"><thead><tr class="text-left"><th class="p-3 w-12"></th><th>Product</th><th>Supplier SKU</th><th class="text-right">Stock</th><th class="text-right">On Order</th><th class="text-right">Reorder</th><th class="text-right">Target</th><th class="text-right w-28">Order Qty</th><th class="text-right">Unit Cost</th><th class="text-right pr-3">Est. Cost</th></tr></thead><tbody><tr v-for="p in g.rows" :key="p.id" class="border-t"><td class="p-3"><input type="checkbox" class="h-5 w-5" :disabled="!canOrder(p)" :checked="isSelected(p.id)" @change="toggleRow(p)"></td><td><b>{{p.name}}</b><div class="text-xs text-slate-500">{{p.sku||'No product code'}}</div><div v-if="!canOrder(p)" class="mt-1 text-xs font-bold text-red-600">{{blockReason(p)}}</div></td><td>{{p.supplier_sku||'—'}}</td><td class="text-right">{{p.stock}}</td><td class="text-right">{{p.on_order}}</td><td class="text-right">{{p.reorder_level}}</td><td class="text-right">{{p.target_stock}}</td><td class="text-right"><input v-model.number="quantities[p.id]" type="number" min="1" step="1" class="input w-24 text-right" :disabled="!isSelected(p.id)"></td><td class="text-right">{{money(p.buy_price)}}</td><td class="text-right pr-3 font-bold">{{money(Number(quantities[p.id]||0)*Number(p.buy_price||0))}}</td></tr></tbody></table></div></section>
<div v-if="!loading&&!groups.length" class="panel mt-5 p-10 text-center"><div class="text-xl font-black text-emerald-700">No products currently require reordering.</div></div>

<Teleport to="body"><div v-if="reviewOpen" class="fixed inset-0 z-[200] flex items-center justify-center bg-slate-950/50 p-4" @click.self="!creating&&(reviewOpen=false)"><div class="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div class="flex items-start justify-between border-b p-5"><div><p class="text-xs font-black uppercase tracking-wider text-blue-600">Purchase Order Consolidation</p><h2 class="text-2xl font-black">Review Draft Purchase Orders</h2><p class="mt-1 text-sm text-slate-500">One draft PO will be created for each supplier below.</p></div><button class="rounded-lg px-3 py-1 text-xl" :disabled="creating" @click="reviewOpen=false">×</button></div>
<div class="space-y-4 p-5"><div v-for="g in selectedGroups" :key="g.key" class="rounded-xl border border-slate-200"><div class="flex justify-between bg-slate-50 p-3"><b>{{g.name}}</b><span>{{g.rows.length}} lines · {{money(groupCost(g))}} ex GST</span></div><div class="divide-y"><div v-for="p in g.rows" :key="p.id" class="flex justify-between gap-4 p-3 text-sm"><span>{{p.name}} <span class="text-slate-400">({{p.supplier_sku}})</span></span><b>{{quantities[p.id]}} × {{money(p.buy_price)}}</b></div></div></div>
<label class="block text-sm font-bold">Expected date <span class="font-normal text-slate-400">(optional, applied to all POs)</span><input v-model="expectedDate" type="date" class="input mt-1 w-full"></label>
<label class="block text-sm font-bold">Notes <span class="font-normal text-slate-400">(optional, applied to all POs)</span><textarea v-model="notes" rows="2" class="input mt-1 w-full" placeholder="Created from Reorder Centre"></textarea></label>
<div v-if="createError" class="rounded-lg bg-red-50 p-3 font-semibold text-red-700">{{createError}}</div></div>
<div class="flex justify-end gap-3 border-t p-5"><button class="btn-secondary" :disabled="creating" @click="reviewOpen=false">Cancel</button><button class="btn-primary" :disabled="creating" @click="createPOs">{{creating?'Creating Draft POs…':`Create ${selectedGroups.length} Draft PO${selectedGroups.length===1?'':'s'}`}}</button></div></div></div></Teleport>
</main></template>
<script setup lang="ts">
definePageMeta({layout:"admin",middleware:["admin"]});const{adminFetch,isSuperAdmin}=useAdminFetch();const router=useRouter();const loading=ref(true),creating=ref(false),err=ref(""),message=ref(""),createError=ref(""),search=ref(""),rows=ref<any[]>([]),selected=ref<number[]>([]),quantities=reactive<Record<number,number>>({}),reviewOpen=ref(false),expectedDate=ref(""),notes=ref("Created from Reorder Centre");
const money=(v:any)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v||0));const reorderRows=computed(()=>rows.value.filter((x:any)=>x.suggested_order>0));const shown=computed(()=>{const q=search.value.toLowerCase().trim();return reorderRows.value.filter((x:any)=>!q||x.name.toLowerCase().includes(q)||String(x.sku||"").toLowerCase().includes(q)||String(x.supplier_name||"").toLowerCase().includes(q))});const makeGroups=(list:any[])=>{const m=new Map<string,any>();for(const p of list){const key=String(p.supplier_id||"none");if(!m.has(key))m.set(key,{key,supplier_id:p.supplier_id,name:p.supplier_name||"No Primary Supplier",rows:[]});m.get(key).rows.push(p)}return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name))};const groups=computed(()=>makeGroups(shown.value));const selectedRows=computed(()=>reorderRows.value.filter((p:any)=>selected.value.includes(Number(p.id))));const selectedGroups=computed(()=>makeGroups(selectedRows.value));const selectedUnits=computed(()=>selectedRows.value.reduce((a:any,p:any)=>a+Number(quantities[p.id]||0),0));const selectedCost=computed(()=>selectedRows.value.reduce((a:any,p:any)=>a+Number(quantities[p.id]||0)*Number(p.buy_price||0),0));const selectedSupplierCount=computed(()=>selectedGroups.value.length);
function canOrder(p:any){return !!p.supplier_id&&!!String(p.supplier_sku||"").trim()&&Number(p.buy_price)>0}function blockReason(p:any){if(!p.supplier_id)return"No primary supplier — fix in Product Data Health";if(!String(p.supplier_sku||"").trim())return"Missing supplier SKU — fix in Product Data Health";if(Number(p.buy_price)<=0)return"Missing buy price — fix in Product Data Health";return""}function isSelected(id:any){return selected.value.includes(Number(id))}function toggleRow(p:any){const id=Number(p.id);if(isSelected(id))selected.value=selected.value.filter(x=>x!==id);else if(canOrder(p)){selected.value.push(id);if(!quantities[id])quantities[id]=Math.max(1,Number(p.suggested_order||1))}}function selectAllShown(){for(const p of shown.value)if(canOrder(p)&&!isSelected(p.id)){selected.value.push(Number(p.id));quantities[p.id]=Math.max(1,Number(p.suggested_order||1))}}function clearSelection(){selected.value=[]}function groupSelected(g:any){const ok=g.rows.filter(canOrder);return !!ok.length&&ok.every((p:any)=>isSelected(p.id))}function toggleGroup(g:any){const ok=g.rows.filter(canOrder);if(groupSelected(g)){const ids=new Set(ok.map((p:any)=>Number(p.id)));selected.value=selected.value.filter(x=>!ids.has(x))}else for(const p of ok)if(!isSelected(p.id)){selected.value.push(Number(p.id));quantities[p.id]=Math.max(1,Number(p.suggested_order||1))}}function groupCost(g:any){return g.rows.reduce((a:any,p:any)=>a+Number(quantities[p.id]||0)*Number(p.buy_price||0),0)}
async function createPOs(){creating.value=true;createError.value="";try{for(const g of selectedGroups.value){const lines=g.rows.map((p:any)=>({product_id:p.id,description:p.name,sku:p.supplier_sku,quantity:Math.max(1,Number(quantities[p.id]||1)),unit_cost_ex_gst:Number(p.buy_price)}));await adminFetch("/api/admin/accounting/purchase-orders",{method:"POST",body:{supplier_id:Number(g.supplier_id),expected_date:expectedDate.value||null,notes:notes.value||"Created from Reorder Centre",status:"draft",lines}})}reviewOpen.value=false;message.value=`Created ${selectedGroups.value.length} draft purchase order${selectedGroups.value.length===1?"":"s"}.`;selected.value=[];await router.push("/admin/purchasing/purchase-orders")}catch(e:any){createError.value=e?.data?.statusMessage||e?.message||"Unable to create purchase orders."}finally{creating.value=false}}
async function load(){loading.value=true;try{if(!isSuperAdmin.value)return navigateTo("/admin");const r:any=await adminFetch("/api/admin/accounting/stock-intelligence");rows.value=r.products||[];for(const p of rows.value)quantities[p.id]=Math.max(1,Number(p.suggested_order||1))}catch(e:any){err.value=e?.data?.statusMessage||e?.message||"Unable to load reorder information."}finally{loading.value=false}}onMounted(load)
</script>
<style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.metric{@apply rounded-xl border border-slate-200 bg-white p-4 shadow-sm}.metric small{@apply block text-xs font-bold uppercase text-slate-500}.metric b{@apply mt-1 block text-2xl}.input{@apply rounded-lg border border-slate-300 bg-white px-3 py-2 outline-none focus:border-blue-500 disabled:bg-slate-100}.btn-primary{@apply rounded-lg bg-blue-600 px-4 py-2 font-bold text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50}.btn-secondary{@apply rounded-lg border border-slate-300 bg-white px-4 py-2 font-bold text-slate-700 hover:bg-slate-50 disabled:opacity-50}</style>