<template><div class="admin-page"><div class="admin-page-inner max-w-[1500px]">
<div class="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><NuxtLink to="/admin/products" class="text-sm font-semibold text-blue-600">← Manage Products</NuxtLink><h1 class="mt-3 text-3xl font-bold text-slate-900">Leader Sync Dashboard</h1><p class="mt-1 text-slate-500">Leader warehouse stock updates automatically. Supplier buy-price changes remain approval-only.</p></div><button class="rounded-lg bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-50" :disabled="busy" @click="scan()">{{busy?`Checking Leader… ${summary.checked}/${summary.total||'?'}`:'Sync All Leader Products'}}</button></div>
<div v-if="error" class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{{error}}</div>
<div class="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><div class="card"><span>Products checked</span><strong>{{summary.checked}}</strong></div><div class="card"><span>Price changes</span><strong>{{summary.priceChanges}}</strong></div><div class="card"><span>Stock changes</span><strong>{{summary.stockChanges}}</strong></div><div class="card"><span>Unchanged</span><strong>{{summary.unchanged}}</strong></div><div class="card"><span>Failed</span><strong :class="summary.failed?'text-red-600':''">{{summary.failed}}</strong></div><div class="card"><span>Last sync</span><strong class="!text-sm">{{lastSync}}</strong></div></div>
<div v-if="rows.length" class="mb-5 flex flex-wrap gap-2"><button v-for="f in filters" :key="f.key" class="rounded-full border px-3 py-1.5 text-xs font-bold" :class="filter===f.key?'border-blue-600 bg-blue-600 text-white':'border-slate-300 bg-white text-slate-600'" @click="filter=f.key">{{f.label}} ({{countFilter(f.key)}})</button><button v-if="summary.failed" class="ml-auto rounded-lg border border-red-300 bg-red-50 px-3 py-1.5 text-xs font-bold text-red-700" :disabled="busy" @click="retryFailed">Retry Failed</button></div>
<div v-if="filteredRows.length" class="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table class="min-w-[1250px] w-full text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-4 text-left">Product</th><th class="p-4 text-right">Current Buy</th><th class="p-4 text-right">Leader Buy</th><th class="p-4 text-right">Price Change</th><th class="p-4 text-left">Leader Stock Change</th><th class="p-4 text-right">Margin</th><th class="p-4 text-right">Action</th></tr></thead><tbody>
<tr v-for="r in filteredRows" :key="r.product_id" class="border-t border-slate-100"><td class="p-4"><p class="font-bold text-slate-900">{{r.name}}</p><p class="text-xs text-slate-500">{{r.sku}}</p><p v-if="r.error" class="mt-1 text-xs font-semibold text-red-600">{{r.error}}</p></td>
<template v-if="r.status==='ok'"><td class="p-4 text-right">{{money(r.current_buy)}}</td><td class="p-4 text-right font-bold">{{money(r.supplier_buy)}}</td><td class="p-4 text-right"><span :class="r.delta>0?'text-red-600':r.delta<0?'text-emerald-600':'text-slate-500'" class="font-bold">{{signedMoney(r.delta)}} <small>({{signed(r.delta_percent)}}%)</small></span></td>
<td class="p-4"><span v-if="r.stock_changed" class="mb-1 inline-block rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">CHANGED</span><p class="whitespace-nowrap text-[11px] text-slate-600">VIC {{stockDiff(r,'VIC')}} · NSW {{stockDiff(r,'NSW')}} · QLD {{stockDiff(r,'QLD')}}</p><p class="mt-1 whitespace-nowrap text-[11px] text-slate-600">SA {{stockDiff(r,'SA')}} · WA {{stockDiff(r,'WA')}}</p></td>
<td class="p-4 text-right"><span class="font-black" :class="r.proposed_margin<10?'text-red-600':r.proposed_margin<20?'text-amber-600':'text-emerald-700'">{{r.proposed_margin.toFixed(1)}}%</span></td><td class="p-4 text-right"><button v-if="r.changed" class="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white" @click="openApply(r)">Review & Apply</button><span v-else class="text-xs font-bold text-emerald-600">Price OK</span></td></template><td v-else colspan="6" class="p-4 text-red-600">Unable to sync</td></tr></tbody></table></div>
<div class="mt-8 rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b p-4"><h2 class="font-black text-slate-900">Sync History</h2><p class="text-xs text-slate-500">The latest 20 Leader sync runs are retained.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[800px] text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-3 text-left">Started</th><th>Duration</th><th>Checked</th><th>Price</th><th>Stock</th><th>Failed</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="h in history" :key="h.id" class="border-t"><td class="p-3">{{dateTime(h.started_at)}}</td><td class="text-center">{{duration(h)}}</td><td class="text-center">{{h.checked_products}} / {{h.total_products}}</td><td class="text-center">{{h.price_changes}}</td><td class="text-center">{{h.stock_changes}}</td><td class="text-center" :class="h.failed_products?'text-red-600 font-bold':''">{{h.failed_products}}</td><td class="text-center"><span class="rounded-full px-2 py-1 text-xs font-bold" :class="h.status==='completed'?'bg-emerald-50 text-emerald-700':h.status==='running'?'bg-blue-50 text-blue-700':'bg-amber-50 text-amber-700'">{{h.status}}</span></td><td class="p-3 text-right"><button class="text-xs font-bold text-blue-600" @click="viewRun(h.id)">View</button></td></tr></tbody></table></div></div>
<Teleport to="body"><div v-if="selected" class="fixed inset-0 z-[2000] flex items-center justify-center bg-slate-950/50 p-4" @click.self="selected=null"><div class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 class="text-xl font-black">Apply supplier price?</h2><p class="mt-2 text-sm text-slate-500">{{selected.name}}</p><div class="mt-4 grid grid-cols-2 gap-3"><div class="card"><span>Current buy</span><strong>{{money(selected.current_buy)}}</strong></div><div class="card"><span>New buy</span><strong>{{money(selected.supplier_buy)}}</strong></div></div><label class="mt-4 flex gap-3 rounded-xl border p-3"><input v-model="recalculate" type="checkbox" class="mt-1"><span><b class="block text-sm">Recalculate store Sell Price and RRP</b><small class="text-slate-500">Off by default.</small></span></label><div class="mt-6 flex justify-end gap-2"><button class="rounded-lg border px-4 py-2 font-bold" @click="selected=null">Cancel</button><button class="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white" @click="applyChange">Apply Update</button></div></div></div></Teleport>
</div></div></template>
<script setup lang="ts">
definePageMeta({layout:'admin',middleware:'admin'});const {adminFetch}=useAdminFetch();const busy=ref(false),error=ref(''),rows=ref<any[]>([]),history=ref<any[]>([]),selected=ref<any>(null),recalculate=ref(false),filter=ref('all');const summary=reactive({checked:0,total:0,priceChanges:0,stockChanges:0,failed:0,unchanged:0});
const filters=[{key:'all',label:'All'},{key:'price',label:'Price Changed'},{key:'stock',label:'Stock Changed'},{key:'failed',label:'Failed'},{key:'unchanged',label:'Unchanged'}];const money=(v:any)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v||0)),signedMoney=(v:any)=>(Number(v)>0?'+':'')+money(v),signed=(v:any)=>(Number(v)>0?'+':'')+Number(v||0).toFixed(2);
const isFailed=(r:any)=>r.status==='error'||r.status==='not_found';const matches=(r:any,k:string)=>k==='all'||(k==='price'&&r.changed)||(k==='stock'&&r.stock_changed)||(k==='failed'&&isFailed(r))||(k==='unchanged'&&r.status==='ok'&&!r.changed&&!r.stock_changed);const filteredRows=computed(()=>rows.value.filter(r=>matches(r,filter.value))),countFilter=(k:string)=>rows.value.filter(r=>matches(r,k)).length;
const lastSync=computed(()=>history.value[0]?.started_at?dateTime(history.value[0].started_at):'Never');function refreshSummary(){summary.checked=rows.value.length;summary.priceChanges=rows.value.filter(r=>r.changed).length;summary.stockChanges=rows.value.filter(r=>r.stock_changed).length;summary.failed=rows.value.filter(isFailed).length;summary.unchanged=rows.value.filter(r=>r.status==='ok'&&!r.changed&&!r.stock_changed).length}
async function loadHistory(){try{const r:any=await adminFetch('/api/admin/products/supplier-sync/history');history.value=r.runs||[]}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Unable to load sync history'}}
async function scan(productIds?:number[]){busy.value=true;error.value='';rows.value=[];Object.assign(summary,{checked:0,total:0,priceChanges:0,stockChanges:0,failed:0,unchanged:0});try{let offset=0,runId:any=null;do{const r:any=await adminFetch('/api/admin/products/supplier-sync/scan',{method:'POST',body:{offset,limit:6,run_id:runId,product_ids:productIds||[]}});runId=r.run_id;summary.total=Number(r.total||0);rows.value.push(...(r.results||[]));refreshSummary();if(r.next_offset==null)break;offset=Number(r.next_offset)}while(true);await loadHistory()}catch(e:any){error.value=e?.data?.statusMessage||e?.data?.message||e?.message||'Unable to sync supplier products'}finally{busy.value=false}}
async function retryFailed(){await scan(rows.value.filter(isFailed).map(r=>Number(r.product_id)).filter(Boolean))}function openApply(r:any){selected.value=r;recalculate.value=false}async function applyChange(){if(!selected.value)return;try{await adminFetch('/api/admin/products/supplier-sync/apply',{method:'POST',body:{product_id:selected.value.product_id,link_id:selected.value.link_id,buy_price_ex_gst:selected.value.supplier_buy,recalculate:recalculate.value}});selected.value.changed=false;selected.value.current_buy=selected.value.supplier_buy;selected.value.delta=0;selected.value.delta_percent=0;selected.value=null;refreshSummary()}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Unable to apply supplier update'}}
const stockDiff=(r:any,k:string)=>{const a=Number(r.old_stock_by_state?.[k]||0),b=Number(r.stock_by_state?.[k]||0);return a===b?String(b):`${a} → ${b}`};const dateTime=(v:any)=>v?new Date(v).toLocaleString('en-AU'):'—';const duration=(h:any)=>{if(!h.completed_at)return h.status==='running'?'Running':'—';const s=Math.max(0,Math.round((new Date(h.completed_at).getTime()-new Date(h.started_at).getTime())/1000));return s<60?`${s}s`:`${Math.floor(s/60)}m ${s%60}s`};async function viewRun(id:number){try{const r:any=await adminFetch(`/api/admin/products/supplier-sync/history?run_id=${id}`);rows.value=(r.results||[]).map((x:any)=>({product_id:x.product_id,link_id:x.supplier_link_id,name:x.product_name,sku:x.sku,status:x.status,error:x.error_message,changed:x.price_changed,stock_changed:x.stock_changed,current_buy:x.old_buy_price,supplier_buy:x.new_buy_price,delta:x.price_delta,delta_percent:x.price_delta_percent,old_stock_by_state:x.old_stock||{},stock_by_state:x.new_stock||{},supplier_stock:Object.values(x.new_stock||{}).reduce((a:any,b:any)=>Number(a)+Number(b||0),0),proposed_margin:0}));summary.total=rows.value.length;refreshSummary();filter.value='all';window.scrollTo({top:0,behavior:'smooth'})}catch(e:any){error.value=e?.data?.statusMessage||e?.message||'Unable to load sync run'}}onMounted(loadHistory);
</script><style scoped>.card{@apply rounded-xl border border-slate-200 bg-white p-4}.card span{@apply block text-xs font-bold uppercase tracking-wide text-slate-500}.card strong{@apply mt-1 block text-xl font-black text-slate-900}</style>
