<template>
  <main class="admin-content">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-4">
      <div><p class="text-xs font-black uppercase tracking-wider text-blue-600">Accounting</p><h1 class="text-3xl font-black">Financial Statements</h1><p class="text-slate-500">Balance Sheet and detailed Profit & Loss from posted journals.</p></div>
      <div class="flex gap-2 print:hidden"><button class="btn-secondary" @click="windowPrint">🖨️ Print / Save PDF</button><NuxtLink class="btn-secondary" to="/admin/accounting">← Accounting</NuxtLink></div>
    </div>
    <section class="admin-panel p-4 print:hidden"><div class="flex flex-wrap items-end gap-3"><label><span>Financial year</span><select v-model="fy" @change="applyFY"><option value="2026">2025–26</option><option value="2027">2026–27</option><option value="custom">Custom</option></select></label><label><span>From</span><input v-model="start" type="date" /></label><label><span>To / Balance Sheet date</span><input v-model="end" type="date" /></label><button class="btn-primary" @click="load">Run Statements</button></div></section>
    <div v-if="err" class="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{{ err }}</div>
    <div v-if="loading" class="mt-4 rounded-xl bg-blue-50 p-4 text-blue-700">Loading financial statements…</div>

    <section class="mt-5"><div class="mb-3 flex items-center justify-between"><div><h2 class="text-2xl font-black">Profit & Loss</h2><p class="text-sm text-slate-500">{{ dateText(start) }} to {{ dateText(end) }}</p></div></div>
      <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div class="metric"><small>Income</small><strong>{{ money(pl?.summary?.income) }}</strong></div><div class="metric"><small>Cost of Goods Sold</small><strong>{{ money(pl?.summary?.cogs) }}</strong></div><div class="metric"><small>Gross Profit</small><strong>{{ money(pl?.summary?.gross_profit) }}</strong><em>{{ pl?.summary?.gross_margin_percent || 0 }}% margin</em></div><div class="metric"><small>Operating Expenses</small><strong>{{ money(pl?.summary?.operating_expenses) }}</strong></div><div class="metric"><small>Net Profit</small><strong>{{ money(pl?.summary?.net_profit) }}</strong></div></div>
      <div class="admin-panel mt-4 overflow-x-auto p-5"><table class="w-full text-sm"><thead><tr><th>Code</th><th>Account</th><th>Section</th><th class="text-right">Amount</th></tr></thead><tbody><template v-for="group in plGroups" :key="group.key"><tr class="section-row"><td colspan="3">{{ group.label }}</td><td class="text-right">{{ money(group.total) }}</td></tr><tr v-for="r in group.rows" :key="r.id"><td class="font-mono">{{ r.code }}</td><td>{{ r.name }}</td><td>{{ group.label }}</td><td class="text-right font-bold">{{ money(r.amount) }}</td></tr></template><tr class="total-row"><td colspan="3">Net Profit</td><td class="text-right">{{ money(pl?.summary?.net_profit) }}</td></tr></tbody></table></div>
    </section>

    <section class="admin-panel mt-5 p-5"><h2 class="text-xl font-black">Monthly Performance</h2><div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Month</th><th class="text-right">Income</th><th class="text-right">COGS</th><th class="text-right">Gross Profit</th><th class="text-right">Expenses</th><th class="text-right">Net Profit</th></tr></thead><tbody><tr v-for="m in pl?.monthly || []" :key="m.month"><td>{{ monthText(m.month) }}</td><td class="text-right">{{ money(m.income) }}</td><td class="text-right">{{ money(m.cogs) }}</td><td class="text-right font-bold">{{ money(m.gross_profit) }}</td><td class="text-right">{{ money(m.operating_expenses) }}</td><td class="text-right font-black">{{ money(m.net_profit) }}</td></tr><tr v-if="!(pl?.monthly||[]).length"><td colspan="6" class="py-6 text-center text-slate-500">No posted activity for this period.</td></tr></tbody></table></div></section>

    <section class="mt-7"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-black">Balance Sheet</h2><p class="text-sm text-slate-500">As at {{ dateText(end) }}</p></div><span :class="bs?.summary?.balanced ? 'balance-ok' : 'balance-bad'">{{ bs?.summary?.balanced ? '✓ Balanced' : `⚠ Difference ${money(bs?.summary?.difference)}` }}</span></div>
      <div class="mt-3 grid gap-3 sm:grid-cols-3"><div class="metric"><small>Total Assets</small><strong>{{ money(bs?.summary?.total_assets) }}</strong></div><div class="metric"><small>Total Liabilities</small><strong>{{ money(bs?.summary?.total_liabilities) }}</strong></div><div class="metric"><small>Total Equity</small><strong>{{ money(bs?.summary?.total_equity) }}</strong></div></div>
      <div class="admin-panel mt-4 p-5"><StatementSection title="Assets" :rows="bs?.assets || []" :total="bs?.summary?.total_assets"/><StatementSection class="mt-6" title="Liabilities" :rows="bs?.liabilities || []" :total="bs?.summary?.total_liabilities"/><div class="mt-6"><h3 class="border-b pb-2 text-lg font-black">Equity</h3><div v-for="r in bs?.equity || []" :key="r.id" class="statement-line"><span><b class="mr-3 font-mono text-xs text-slate-400">{{ r.code }}</b>{{ r.name }}</span><strong>{{ money(r.balance) }}</strong></div><div class="statement-line"><span>Current Earnings</span><strong>{{ money(bs?.current_earnings) }}</strong></div><div class="statement-total"><span>Total Equity</span><strong>{{ money(bs?.summary?.total_equity) }}</strong></div></div><div class="grand-total"><span>Total Liabilities &amp; Equity</span><strong>{{ money(bs?.summary?.liabilities_and_equity) }}</strong></div></div>
    </section>

    <section class="admin-panel mt-5 p-5 print:hidden"><details><summary class="cursor-pointer text-lg font-black">Transaction Drill-down ({{ pl?.transactions?.length || 0 }})</summary><div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Date</th><th>Reference</th><th>Account</th><th>Description</th><th class="text-right">Amount</th></tr></thead><tbody><tr v-for="t in pl?.transactions || []" :key="t.id"><td>{{ t.date }}</td><td>{{ t.reference || '—' }}</td><td>{{ t.account_code }} · {{ t.account_name }}</td><td>{{ t.description || '—' }}</td><td class="text-right font-bold">{{ money(t.amount) }}</td></tr></tbody></table></div></details></section>
  </main>
</template>
<script setup lang="ts">
definePageMeta({layout:'admin',middleware:['admin']});
const {adminFetch,isSuperAdmin}=useAdminFetch(); const now=new Date(); const currentFY=now.getMonth()>=6?now.getFullYear()+1:now.getFullYear();
const fy=ref(String(currentFY)); const start=ref(''),end=ref(''),pl=ref<any>(null),bs=ref<any>(null),err=ref(''),loading=ref(false);
const money=(v:any)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v||0)); const dateText=(v:string)=>v?new Date(`${v}T00:00:00`).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'}):''; const monthText=(v:string)=>new Date(`${v}-01T00:00:00`).toLocaleDateString('en-AU',{month:'short',year:'numeric'});
function applyFY(){if(fy.value==='custom')return;const y=Number(fy.value);start.value=`${y-1}-07-01`;end.value=`${y}-06-30`;}
const plGroups=computed(()=>[{key:'income',label:'Income',rows:(pl.value?.rows||[]).filter((x:any)=>x.group==='income'),total:pl.value?.summary?.income},{key:'cogs',label:'Cost of Goods Sold',rows:(pl.value?.rows||[]).filter((x:any)=>x.group==='cogs'),total:pl.value?.summary?.cogs},{key:'expenses',label:'Operating Expenses',rows:(pl.value?.rows||[]).filter((x:any)=>x.group==='operating_expenses'),total:pl.value?.summary?.operating_expenses}]);
async function load(){err.value='';loading.value=true;try{if(!isSuperAdmin.value)return navigateTo('/admin');[pl.value,bs.value]=await Promise.all([adminFetch(`/api/admin/accounting/reports/profit-loss-detailed?start=${start.value}&end=${end.value}`),adminFetch(`/api/admin/accounting/reports/balance-sheet?as_of=${end.value}`)])}catch(e:any){err.value=e?.data?.statusMessage||e?.message||'Unable to load financial statements.'}finally{loading.value=false}}
function windowPrint(){window.print()} applyFY(); onMounted(load);
const StatementSection=defineComponent({props:{title:String,rows:{type:Array,default:()=>[]},total:Number},setup(p){return()=>h('div',[h('h3',{class:'border-b pb-2 text-lg font-black'},p.title),...(p.rows as any[]).map(r=>h('div',{class:'statement-line'},[h('span',[h('b',{class:'mr-3 font-mono text-xs text-slate-400'},String(r.code)),String(r.name)]),h('strong',money(r.balance))])),h('div',{class:'statement-total'},[h('span',`Total ${p.title}`),h('strong',money(p.total))])])}});
</script>
<style scoped>
.admin-panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.metric{@apply rounded-xl border border-slate-200 bg-white p-4 shadow-sm}.metric small{@apply block text-xs font-bold uppercase tracking-wide text-slate-500}.metric strong{@apply mt-1 block text-xl font-black}.metric em{@apply mt-1 block text-xs not-italic text-slate-500}.btn-primary{@apply rounded-lg bg-blue-600 px-4 py-2 text-sm font-black text-white hover:bg-blue-700}.btn-secondary{@apply rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-bold}label span{@apply mb-1 block text-xs font-bold text-slate-500}input,select{@apply rounded-lg border border-slate-300 bg-white px-3 py-2}th{@apply border-b p-2 text-left text-xs uppercase tracking-wide text-slate-500}td{@apply border-b p-2}.section-row{@apply bg-slate-50 font-black}.total-row{@apply bg-slate-900 text-base font-black text-white}.statement-line{@apply flex justify-between gap-4 border-b border-slate-100 py-2 text-sm}.statement-total{@apply mt-2 flex justify-between border-t-2 border-slate-300 pt-2 font-black}.grand-total{@apply mt-6 flex justify-between rounded-xl bg-slate-900 p-4 text-lg font-black text-white}.balance-ok{@apply rounded-full bg-emerald-100 px-3 py-1 text-sm font-black text-emerald-700}.balance-bad{@apply rounded-full bg-red-100 px-3 py-1 text-sm font-black text-red-700}
@media print{.admin-content{padding:0!important}.admin-panel,.metric{box-shadow:none!important}.print\:hidden{display:none!important}}
</style>
