<template><main class="admin-content">
<NuxtLink to="/admin/accounting" class="text-sm font-bold text-blue-600">← Accounting</NuxtLink>
<div class="mt-2 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-wider text-blue-600">SuperAdmin</p><h1 class="text-3xl font-black">Inventory & COGS</h1><p class="text-slate-500">Inventory valuation and cost of goods sold from posted sales.</p></div><div class="flex flex-wrap gap-2"><label><span class="label">From</span><input v-model="start" type="date" class="input"></label><label><span class="label">To</span><input v-model="end" type="date" class="input"></label><button class="btn-primary" @click="load">Run Report</button></div></div>
<div v-if="err" class="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{{err}}</div>
<div class="mt-5 grid gap-4 md:grid-cols-4"><div class="panel p-5"><small>Inventory Value</small><div class="metric">{{money(data.summary?.inventory_value)}}</div></div><div class="panel p-5"><small>Retail Value</small><div class="metric">{{money(data.summary?.retail_value)}}</div></div><div class="panel p-5"><small>Units on Hand</small><div class="metric">{{num(data.summary?.units_on_hand)}}</div></div><div class="panel p-5"><small>COGS for Period</small><div class="metric">{{money(data.summary?.period_cogs)}}</div></div></div>
<section class="panel mt-5 overflow-hidden"><div class="p-5"><h2 class="text-xl font-black">Current Inventory Valuation</h2><p class="text-sm text-slate-500">Stock on hand × current buy price ex GST.</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">Product</th><th>SKU</th><th class="text-right">Stock</th><th class="text-right">Unit Cost</th><th class="text-right">Inventory Value</th><th class="text-right">Retail Value</th><th class="text-right pr-3">Potential Margin</th></tr></thead><tbody><tr v-for="x in data.valuation" :key="x.id" class="border-t"><td class="p-3 font-bold">{{x.name}}</td><td>{{x.sku}}</td><td class="text-right">{{num(x.stock)}}</td><td class="text-right">{{money(x.unit_cost)}}</td><td class="text-right font-bold">{{money(x.value)}}</td><td class="text-right">{{money(x.retail_value)}}</td><td class="text-right pr-3">{{money(x.potential_margin)}}</td></tr></tbody></table></div></section>
<section class="panel mt-5 overflow-hidden"><div class="p-5"><h2 class="text-xl font-black">COGS by Product</h2><p class="text-sm text-slate-500">Historical cost captured when an online order is posted to accounting.</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">Product</th><th>SKU</th><th class="text-right">Qty Sold</th><th class="text-right pr-3">COGS</th></tr></thead><tbody><tr v-for="x in data.profitability" :key="x.product_id" class="border-t"><td class="p-3 font-bold">{{x.name}}</td><td>{{x.sku}}</td><td class="text-right">{{num(x.quantity_sold)}}</td><td class="text-right pr-3 font-bold">{{money(x.cogs)}}</td></tr><tr v-if="!data.profitability?.length"><td colspan="4" class="p-6 text-center text-slate-500">No COGS movements in this period yet.</td></tr></tbody></table></div></section>
<section class="panel mt-5 overflow-hidden"><div class="p-5"><h2 class="text-xl font-black">Stock Movement Ledger</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="bg-slate-50 text-left"><th class="p-3">Date</th><th>Product</th><th>Type</th><th>Source</th><th class="text-right">Qty</th><th class="text-right pr-3">Cost</th></tr></thead><tbody><tr v-for="x in data.movements" :key="x.id" class="border-t"><td class="p-3">{{x.movement_date}}</td><td class="font-bold">{{x.products?.name||x.product_id}}</td><td class="capitalize">{{String(x.movement_type).replace('_',' ')}}</td><td>{{x.source_type}} {{x.source_id||''}}</td><td class="text-right">{{num(x.quantity)}}</td><td class="text-right pr-3">{{money(x.total_cost_ex_gst)}}</td></tr></tbody></table></div></section>
</main></template>
<script setup lang="ts">definePageMeta({layout:"admin",middleware:["admin"]});const{adminFetch,isSuperAdmin}=useAdminFetch();const now=new Date(),fy=now.getMonth()>=6?now.getFullYear():now.getFullYear()-1;const start=ref(`${fy}-07-01`),end=ref(`${fy+1}-06-30`),err=ref(""),data=reactive<any>({summary:{},valuation:[],profitability:[],movements:[]});const money=(v:any)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v||0));const num=(v:any)=>new Intl.NumberFormat("en-AU",{maximumFractionDigits:3}).format(Number(v||0));async function load(){err.value="";try{if(!isSuperAdmin.value)return navigateTo("/admin");Object.assign(data,await adminFetch(`/api/admin/accounting/inventory/report?start=${start.value}&end=${end.value}`))}catch(e:any){err.value=e?.data?.statusMessage||e.message}}onMounted(load)</script>
<style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.metric{@apply mt-1 text-2xl font-black}.label{@apply mb-1 block text-xs font-bold text-slate-600}.input{@apply rounded-lg border border-slate-300 px-3 py-2}.btn-primary{@apply self-end rounded-lg bg-blue-600 px-5 py-2.5 font-bold text-white}</style>
