<template><main class="admin-content">
  <div class="no-print flex flex-wrap items-end justify-between gap-3"><div><NuxtLink to="/admin/accounting" class="text-sm font-bold text-blue-600">← Accounting</NuxtLink><h1 class="mt-2 text-3xl font-black">💼 Business Management Report</h1><p class="text-slate-500">Owner-level view of sales, profitability, cash commitments and business health.</p></div><div class="flex gap-2"><button class="btn" @click="load">Refresh</button><button class="btn" @click="printReport">Print / Save PDF</button></div></div>
  <section class="panel no-print mt-5 p-4"><div class="flex flex-wrap items-end gap-3"><label><span>Period</span><select v-model="preset" @change="applyPreset"><option value="fy">Current Financial Year</option><option value="lastfy">Last Financial Year</option><option value="month">This Month</option><option value="lastmonth">Last Month</option><option value="custom">Custom</option></select></label><label><span>From</span><input v-model="start" type="date" @change="preset='custom'"/></label><label><span>To</span><input v-model="end" type="date" @change="preset='custom'"/></label><button class="btn-primary" @click="load">Run Report</button></div></section>
  <div v-if="err" class="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{{err}}</div>
  <div v-if="loading" class="mt-6 text-slate-500">Building management report…</div>
  <template v-else-if="report">
    <div class="print-head mt-6"><h2 class="text-2xl font-black">Kialla Computers — Business Management Report</h2><p>{{date(start)}} to {{date(end)}}</p></div>
    <section class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><div v-for="m in metrics" :key="m.label" class="metric"><small>{{m.label}}</small><b>{{m.value}}</b><span :class="m.tone">{{m.sub}}</span></div></section>
    <section class="mt-5 grid gap-5 xl:grid-cols-3"><div class="panel p-5 xl:col-span-2"><h2 class="text-xl font-black">Performance Trend</h2><p class="text-sm text-slate-500">Posted accounting income and expenses for the selected period.</p><div class="mt-5 flex h-52 items-end gap-2"><div v-for="m in report.monthly||[]" :key="m.month" class="flex min-w-0 flex-1 flex-col items-center gap-1"><div class="flex h-40 w-full items-end justify-center gap-1"><div class="w-2/5 rounded-t bg-emerald-300" :style="{height:bar(m.income)}"></div><div class="w-2/5 rounded-t bg-slate-300" :style="{height:bar(m.expenses)}"></div></div><span class="text-[10px] font-bold text-slate-500">{{month(m.month)}}</span></div><p v-if="!report.monthly?.length" class="m-auto text-sm text-slate-400">No posted activity.</p></div><div class="mt-3 flex gap-4 text-xs"><span>🟩 Income</span><span>⬜ Expenses</span></div></div>
      <div class="panel p-5"><h2 class="text-xl font-black">Needs Attention</h2><div class="mt-3 space-y-2"><NuxtLink v-for="a in report.attention||[]" :key="a.label" :to="a.to" class="block rounded-xl border border-slate-200 p-3 hover:bg-slate-50"><div class="font-bold">{{a.label}}</div><div class="mt-1 text-sm" :class="a.level==='high'?'text-red-600':'text-amber-700'">{{a.value!==undefined?money(a.value):a.count}}</div></NuxtLink><div v-if="!report.attention?.length" class="rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">No immediate accounting items require attention.</div></div></div></section>
    <section class="mt-5 grid gap-5 lg:grid-cols-2"><div class="panel p-5"><h2 class="text-xl font-black">Sales & Gross Profit</h2><div class="rows"><p><span>Orders</span><b>{{report.sales.orders}}</b></p><p><span>Units sold</span><b>{{report.sales.units}}</b></p><p><span>Sales ex GST</span><b>{{money(report.sales.revenue)}}</b></p><p><span>Historical COGS</span><b>{{money(report.sales.cogs)}}</b></p><p><span>Gross profit</span><b>{{money(report.sales.gross_profit)}}</b></p><p><span>Gross margin</span><b>{{pct(report.sales.margin)}}</b></p><p><span>Average order</span><b>{{money(report.sales.average_order)}}</b></p></div></div><div class="panel p-5"><h2 class="text-xl font-black">Financial Position</h2><div class="rows"><p><span>Customers owe</span><b>{{money(report.position.receivables)}}</b></p><p><span>Overdue receivables</span><b>{{money(report.position.overdue_receivables)}}</b></p><p><span>Supplier bills owing</span><b>{{money(report.position.payables)}}</b></p><p><span>Overdue payables</span><b>{{money(report.position.overdue_payables)}}</b></p><p><span>Inventory value</span><b>{{money(report.position.inventory_value)}}</b></p><p><span>Open purchase orders</span><b>{{report.position.open_purchase_orders}}</b></p><p><span>Bank items to reconcile</span><b>{{report.position.unreconciled_bank}}</b></p></div></div></section>
    <section class="panel mt-5 p-5"><h2 class="text-xl font-black">Period Comparison</h2><p class="text-sm text-slate-500">Compared with {{date(report.period.previous_start)}} to {{date(report.period.previous_end)}}.</p><div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="compare"><span>Sales movement</span><b :class="tone(report.sales.revenue_change_pct)">{{signed(report.sales.revenue_change_pct)}}</b></div><div class="compare"><span>Gross profit movement</span><b :class="tone(report.sales.profit_change_pct)">{{signed(report.sales.profit_change_pct)}}</b></div><div class="compare"><span>Order movement</span><b :class="tone(report.sales.orders_change_pct)">{{signed(report.sales.orders_change_pct)}}</b></div></div></section>
    <div class="no-print mt-5 flex flex-wrap gap-2"><NuxtLink class="btn" to="/admin/accounting/profitability">Sales Analytics</NuxtLink><NuxtLink class="btn" to="/admin/accounting/cash-flow">Cash Flow</NuxtLink><NuxtLink class="btn" to="/admin/accounting/stock-intelligence">Stock Intelligence</NuxtLink><NuxtLink class="btn" to="/admin/accounting/financial-statements">Financial Statements</NuxtLink></div>
  </template>
</main></template>
<script setup lang="ts">
definePageMeta({middleware:'admin'}); const { isSuperAdmin, adminFetch, checkAdmin, adminChecked } = useAdminFetch();
const now=new Date(), fy=now.getMonth()>=6?now.getFullYear():now.getFullYear()-1; const iso=(d:Date)=>d.toISOString().slice(0,10);
const preset=ref('fy'),start=ref(`${fy}-07-01`),end=ref(`${fy+1}-06-30`),report=ref<any>(null),loading=ref(false),err=ref('');
const money=(v:any)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v||0)),pct=(v:any)=>`${Number(v||0).toFixed(1)}%`,date=(v:any)=>v?new Date(String(v)+'T00:00:00').toLocaleDateString('en-AU'):'—',month=(v:string)=>new Date(v+'-01T00:00:00').toLocaleDateString('en-AU',{month:'short'});
function applyPreset(){const d=new Date();if(preset.value==='fy'){start.value=`${fy}-07-01`;end.value=`${fy+1}-06-30`}else if(preset.value==='lastfy'){start.value=`${fy-1}-07-01`;end.value=`${fy}-06-30`}else if(preset.value==='month'){start.value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;end.value=iso(new Date(d.getFullYear(),d.getMonth()+1,0))}else if(preset.value==='lastmonth'){const x=new Date(d.getFullYear(),d.getMonth()-1,1);start.value=iso(x);end.value=iso(new Date(x.getFullYear(),x.getMonth()+1,0))}if(preset.value!=='custom')load()}
async function load(){loading.value=true;err.value='';try{if(!adminChecked.value) await checkAdmin(); if(!isSuperAdmin.value){err.value='SuperAdmin access is required to view this report.';return}report.value=await adminFetch(`/api/admin/accounting/management-report?start=${start.value}&end=${end.value}`)}catch(e:any){err.value=e?.data?.statusMessage||e?.message||'Unable to build report.'}finally{loading.value=false}}
const metrics=computed(()=>{const x=report.value;if(!x)return[];return[{label:'Sales ex GST',value:money(x.sales.revenue),sub:`${signed(x.sales.revenue_change_pct)} vs prior`,tone:tone(x.sales.revenue_change_pct)},{label:'Gross Profit',value:money(x.sales.gross_profit),sub:`${pct(x.sales.margin)} margin`,tone:''},{label:'Net Profit',value:money(x.accounting.net_profit),sub:'Posted journals',tone:tone(x.accounting.net_profit)},{label:'Customers Owe',value:money(x.position.receivables),sub:`${money(x.position.overdue_receivables)} overdue`,tone:x.position.overdue_receivables?'text-red-600':''},{label:'Bills Owing',value:money(x.position.payables),sub:`${money(x.position.overdue_payables)} overdue`,tone:x.position.overdue_payables?'text-red-600':''},{label:'Inventory',value:money(x.position.inventory_value),sub:'Current buy cost',tone:''},{label:'Open POs',value:String(x.position.open_purchase_orders),sub:'Purchasing commitments',tone:''}]});
function printReport(){ if(import.meta.client) window.print() }
const maxChart=computed(()=>Math.max(1,...(report.value?.monthly||[]).flatMap((x:any)=>[Number(x.income||0),Number(x.expenses||0)])));const bar=(v:any)=>`${Math.max(2,Math.round(Number(v||0)/maxChart.value*100))}%`;const tone=(v:any)=>Number(v)>0?'text-emerald-700':Number(v)<0?'text-red-600':'text-slate-500';const signed=(v:any)=>`${Number(v)>0?'+':''}${Number(v||0).toFixed(1)}%`;
onMounted(load);
</script>
<style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.metric{@apply flex min-h-28 flex-col rounded-xl border border-slate-200 bg-white p-4 shadow-sm}.metric small{@apply text-xs font-black uppercase tracking-wide text-slate-500}.metric b{@apply mt-2 text-xl font-black}.metric span{@apply mt-auto pt-2 text-xs}.btn{@apply rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-bold hover:bg-slate-50}.btn-primary{@apply rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white}label span{@apply mb-1 block text-xs font-black uppercase text-slate-500}select,input{@apply rounded-lg border border-slate-300 bg-white px-3 py-2}.rows p{@apply flex justify-between gap-4 border-b border-slate-100 py-3}.rows p:last-child{@apply border-b-0}.compare{@apply rounded-xl bg-slate-50 p-4}.compare span{@apply block text-xs font-black uppercase text-slate-500}.compare b{@apply mt-2 block text-2xl font-black}.print-head{@apply hidden}@media print{.no-print{display:none!important}.print-head{display:block!important}.panel,.metric{box-shadow:none!important;break-inside:avoid}.admin-content{padding:0!important}}</style>
