<template>
<main class="admin-content"><AdminPurchasingWorkflow /><NuxtLink to="/admin/accounting" class="text-sm font-bold text-blue-600">← Accounting</NuxtLink>
<div class="mt-2 flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-wider text-blue-600">SuperAdmin</p><h1 class="text-3xl font-black">Accounts Payable</h1><p class="text-slate-500">Supplier bills, ageing and payments.</p></div><NuxtLink to="/admin/accounting/purchases" class="secondary">Suppliers & Purchase Orders</NuxtLink></div>
<div v-if="msg" class="mt-4 rounded-lg bg-slate-100 p-3">{{msg}}</div>
<div class="mt-5 grid gap-4 md:grid-cols-4"><div class="panel p-5"><small>Total Outstanding</small><div class="text-2xl font-black">{{money(totalOutstanding)}}</div></div><div class="panel p-5"><small>Overdue</small><div class="text-2xl font-black text-red-600">{{money(overdueTotal)}}</div></div><div class="panel p-5"><small>Due in 7 Days</small><div class="text-2xl font-black">{{money(dueSoonTotal)}}</div></div><div class="panel p-5"><small>Open Bills</small><div class="text-3xl font-black">{{openBills.length}}</div></div></div>
<section class="panel mt-5 p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-black">Payables Ageing</h2><p class="text-sm text-slate-500">Outstanding supplier bills by due date.</p></div><select v-model="filter" class="input max-w-48"><option value="all">All open bills</option><option value="current">Current</option><option value="1-30">1–30 overdue</option><option value="31-60">31–60 overdue</option><option value="61-90">61–90 overdue</option><option value="90+">90+ overdue</option></select></div>
<div class="mt-4 grid gap-3 sm:grid-cols-5"><div v-for="a in ageingCards" :key="a.key" class="rounded-xl border p-3"><div class="text-xs font-bold text-slate-500">{{a.label}}</div><div class="mt-1 text-lg font-black">{{money(a.value)}}</div></div></div>
<div class="mt-4 overflow-x-auto"><table class="w-full min-w-[950px] text-sm"><thead><tr class="border-b text-left"><th class="p-2">Bill</th><th>Supplier</th><th>Supplier Invoice</th><th>Bill Date</th><th>Due Date</th><th>Status</th><th class="text-right">Total</th><th class="text-right">Paid</th><th class="text-right">Owing</th><th></th></tr></thead><tbody><tr v-for="b in filteredBills" :key="b.id" class="border-b"><td class="p-2 font-bold">{{b.bill_number}}</td><td>{{b.accounting_suppliers?.name}}</td><td>{{b.supplier_invoice_number||'—'}}</td><td>{{b.bill_date}}</td><td><span :class="isOverdue(b)?'font-bold text-red-600':''">{{b.due_date||'—'}}</span></td><td><span class="badge">{{displayStatus(b)}}</span></td><td class="text-right">{{money(b.total)}}</td><td class="text-right">{{money(b.paid_amount)}}</td><td class="text-right font-black">{{money(owing(b))}}</td><td class="text-right"><button class="primary" @click="openPayment(b)">Record Payment</button></td></tr><tr v-if="!filteredBills.length"><td colspan="10" class="p-8 text-center text-slate-500">No bills in this ageing group.</td></tr></tbody></table></div></section>
<section class="panel mt-5 p-5"><h2 class="text-xl font-black">Recent Supplier Payments</h2><div class="mt-3 overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b text-left"><th class="p-2">Date</th><th>Supplier</th><th>Bill</th><th>Reference</th><th class="text-right">Amount</th></tr></thead><tbody><tr v-for="p in payments.slice(0,20)" :key="p.id" class="border-b"><td class="p-2">{{String(p.created_at||'').slice(0,10)}}</td><td>{{p.accounting_supplier_bills?.accounting_suppliers?.name||'—'}}</td><td>{{p.accounting_supplier_bills?.bill_number||'—'}}</td><td>{{p.reference||'—'}}</td><td class="text-right font-bold">{{money(p.amount)}}</td></tr></tbody></table></div></section>
<div v-if="paymentBill" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" @click.self="paymentBill=null"><div class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 class="text-xl font-black">Record Supplier Payment</h2><p class="mt-1 text-sm text-slate-500">{{paymentBill.accounting_suppliers?.name}} · {{paymentBill.bill_number}}</p><div class="mt-4 rounded-xl bg-slate-50 p-4"><div class="flex justify-between"><span>Outstanding</span><b>{{money(owing(paymentBill))}}</b></div></div><label class="label">Amount</label><input v-model.number="payment.amount" class="input" type="number" min="0.01" step="0.01"><label class="label">Reference</label><input v-model="payment.reference" class="input" placeholder="EFT / bank reference"><div class="mt-5 flex justify-end gap-2"><button class="secondary" @click="paymentBill=null">Cancel</button><button class="primary" :disabled="saving" @click="savePayment">{{saving?'Saving…':'Record Payment'}}</button></div></div></div>
</main></template>
<script setup lang="ts">
definePageMeta({layout:"admin",middleware:["admin"]}); const{adminFetch,isSuperAdmin}=useAdminFetch(); const bills=ref<any[]>([]),payments=ref<any[]>([]),msg=ref(""),filter=ref("all"),paymentBill=ref<any>(null),saving=ref(false); const payment=reactive({amount:0,reference:""});
const money=(v:any)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v||0)); const owing=(b:any)=>Math.max(0,Number(b.total||0)-Number(b.paid_amount||0)); const today=()=>new Date(new Date().toISOString().slice(0,10)+"T00:00:00");
function daysOverdue(b:any){if(!b.due_date)return 0;return Math.floor((today().getTime()-new Date(b.due_date+"T00:00:00").getTime())/86400000)} function isOverdue(b:any){return owing(b)>0&&daysOverdue(b)>0} function bucket(b:any){const d=daysOverdue(b);if(d<=0)return"current";if(d<=30)return"1-30";if(d<=60)return"31-60";if(d<=90)return"61-90";return"90+"} function displayStatus(b:any){if(owing(b)<=0)return"Paid";if(isOverdue(b))return b.status==="part_paid"?"Part Paid · Overdue":"Overdue";return b.status==="part_paid"?"Part Paid":"Current"}
const openBills=computed(()=>bills.value.filter(b=>owing(b)>0)); const totalOutstanding=computed(()=>openBills.value.reduce((s,b)=>s+owing(b),0)); const overdueTotal=computed(()=>openBills.value.filter(isOverdue).reduce((s,b)=>s+owing(b),0)); const dueSoonTotal=computed(()=>openBills.value.filter(b=>{if(!b.due_date)return false;const d=-daysOverdue(b);return d>=0&&d<=7}).reduce((s,b)=>s+owing(b),0)); const ageingCards=computed(()=>[{key:"current",label:"Current",value:openBills.value.filter(b=>bucket(b)==="current").reduce((s,b)=>s+owing(b),0)},{key:"1-30",label:"1–30 Days",value:openBills.value.filter(b=>bucket(b)==="1-30").reduce((s,b)=>s+owing(b),0)},{key:"31-60",label:"31–60 Days",value:openBills.value.filter(b=>bucket(b)==="31-60").reduce((s,b)=>s+owing(b),0)},{key:"61-90",label:"61–90 Days",value:openBills.value.filter(b=>bucket(b)==="61-90").reduce((s,b)=>s+owing(b),0)},{key:"90+",label:"90+ Days",value:openBills.value.filter(b=>bucket(b)==="90+").reduce((s,b)=>s+owing(b),0)}]); const filteredBills=computed(()=>openBills.value.filter(b=>filter.value==="all"||bucket(b)===filter.value));
async function load(){msg.value="";try{if(!isSuperAdmin.value)return navigateTo("/admin");[bills.value,payments.value]=await Promise.all([adminFetch("/api/admin/accounting/supplier-bills"),adminFetch("/api/admin/accounting/supplier-payments")])}catch(e:any){msg.value=e?.data?.statusMessage||e.message}} function openPayment(b:any){paymentBill.value=b;payment.amount=owing(b);payment.reference=""} async function savePayment(){if(!paymentBill.value)return;saving.value=true;try{await adminFetch("/api/admin/accounting/supplier-payments",{method:"POST",body:{bill_id:paymentBill.value.id,amount:Number(payment.amount),reference:payment.reference}});paymentBill.value=null;msg.value="Supplier payment posted to Accounts Payable and the bank ledger.";await load()}catch(e:any){msg.value=e?.data?.statusMessage||e.message}finally{saving.value=false}} onMounted(load)
</script>
<style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.input{@apply w-full rounded-lg border border-slate-300 px-3 py-2 text-sm}.primary{@apply rounded-lg bg-blue-600 px-3 py-2 text-sm font-bold text-white disabled:opacity-50}.secondary{@apply rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-bold}.badge{@apply rounded-full bg-slate-100 px-2 py-1 text-xs font-bold}.label{@apply mb-1 mt-4 block text-sm font-bold}</style>
