<template><main class="admin-content"><div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-wider text-blue-600">Accounting Analytics</p><h1 class="text-3xl font-black">Sales & Profitability Analytics</h1><p class="text-slate-500">Revenue, historical COGS, gross profit and margins by product, category and customer.</p></div><NuxtLink to="/admin/accounting" class="btn-secondary">← Accounting</NuxtLink></div>
<div v-if="err" class="mb-4 rounded-xl bg-red-50 p-4 text-red-700">{{err}}</div>
<section class="panel p-5"><div class="flex flex-wrap items-end gap-3"><label class="field"><span>Period</span><select v-model="preset" @change="applyPreset"><option value="month">This Month</option><option value="lastmonth">Last Month</option><option value="quarter">This Quarter</option><option value="fy">Current Financial Year</option><option value="lastfy">Last Financial Year</option><option value="custom">Custom</option></select></label><label class="field"><span>From</span><input v-model="start" type="date" @change="preset='custom'"></label><label class="field"><span>To</span><input v-model="end" type="date" @change="preset='custom'"></label><button class="btn-primary" @click="load">Run Report</button><button class="btn-secondary" @click="exportCsv">Export Product CSV</button></div></section>
<section class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><div class="metric"><small>Sales ex GST</small><b>{{money(data.summary?.revenue_ex_gst)}}</b></div><div class="metric"><small>COGS</small><b>{{money(data.summary?.cogs)}}</b></div><div class="metric"><small>Gross Profit</small><b :class="num(data.summary?.gross_profit)<0?'text-red-600':'text-emerald-700'">{{money(data.summary?.gross_profit)}}</b></div><div class="metric"><small>Gross Margin</small><b>{{pct(data.summary?.gross_margin_pct)}}</b></div><div class="metric"><small>Orders</small><b>{{data.summary?.orders||0}}</b></div><div class="metric"><small>Units Sold</small><b>{{data.summary?.units||0}}</b></div><div class="metric"><small>Avg Order ex GST</small><b>{{money(data.summary?.average_order_ex_gst)}}</b></div></section>
<section class="panel mt-5 p-5"><div class="flex flex-wrap gap-2"><button v-for="t in tabs" :key="t.key" class="tab" :class="{active:tab===t.key}" @click="tab=t.key">{{t.label}}</button></div>
<div v-if="tab==='overview'" class="mt-5 grid gap-5 xl:grid-cols-2"><div class="box"><h2>Monthly Performance</h2><div class="mt-4 flex h-52 items-end gap-2"><div v-for="m in data.monthly||[]" :key="m.month" class="flex min-w-0 flex-1 flex-col items-center gap-1"><div class="flex h-40 w-full items-end justify-center gap-1"><div class="w-1/3 rounded-t bg-blue-300" :style="{height:bar(m.revenue_ex_gst)}" :title="money(m.revenue_ex_gst)"></div><div class="w-1/3 rounded-t bg-emerald-300" :style="{height:bar(Math.max(0,m.profit))}" :title="money(m.profit)"></div></div><span class="text-[10px] font-bold text-slate-500">{{month(m.month)}}</span></div><p v-if="!(data.monthly||[]).length" class="m-auto text-sm text-slate-500">No sales in this period.</p></div><div class="mt-3 text-xs text-slate-500">Blue = sales ex GST · Green = gross profit</div></div><div class="box"><h2>Margin Watch</h2><p class="text-sm text-slate-500">Current catalogue prices compared with current buy cost. This is a pricing warning, not historical profit.</p><div class="mt-3 max-h-64 overflow-auto"><div v-for="x in lowMargins" :key="x.id" class="flex justify-between gap-3 border-t py-2 text-sm"><div><b>{{x.name}}</b><div class="text-xs text-slate-500">{{x.sku}} · {{x.category}}</div></div><div class="text-right"><b :class="x.margin_pct<20?'text-red-600':x.margin_pct<30?'text-amber-600':'text-slate-700'">{{pct(x.margin_pct)}}</b><div class="text-xs text-slate-500">{{money(x.profit_ex_gst)}} / unit</div></div></div></div></div></div>
<div v-else class="mt-5 overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b text-left"><th class="p-2">{{firstHeader}}</th><th v-if="tab==='products'">Category</th><th class="text-right">{{tab==='products'||tab==='categories'?'Qty':'Orders'}}</th><th class="text-right">Sales ex GST</th><th class="text-right">COGS</th><th class="text-right">Gross Profit</th><th class="text-right">Margin</th></tr></thead><tbody><tr v-for="(x,i) in activeRows" :key="i" class="border-b"><td class="p-2"><b>{{rowName(x)}}</b><div v-if="x.sku||x.email" class="text-xs text-slate-500">{{x.sku||x.email}}</div></td><td v-if="tab==='products'">{{x.category}}</td><td class="text-right">{{tab==='customers'?x.orders:x.quantity}}</td><td class="text-right">{{money(x.revenue_ex_gst)}}</td><td class="text-right">{{money(x.cogs)}}</td><td class="text-right font-bold" :class="num(x.profit)<0?'text-red-600':'text-emerald-700'">{{money(x.profit)}}</td><td class="text-right font-bold">{{pct(x.margin_pct)}}</td></tr></tbody></table></div></section>
</main></template>
<script setup lang="ts">
definePageMeta({layout:'admin',middleware:['admin']}); const {adminFetch,isSuperAdmin}=useAdminFetch();
const data=ref<any>({summary:{},products:[],categories:[],customers:[],monthly:[],margin_alerts:[]}),err=ref(''),tab=ref('overview'),preset=ref('fy'),start=ref(''),end=ref('');
const tabs=[{key:'overview',label:'Overview'},{key:'products',label:'Products'},{key:'categories',label:'Categories'},{key:'customers',label:'Customers'}]; const num=(v:any)=>Number(v||0); const money=(v:any)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(num(v)); const pct=(v:any)=>`${num(v).toFixed(1)}%`; const iso=(d:Date)=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
function applyPreset(){const now=new Date(),y=now.getFullYear(),m=now.getMonth(); let s:Date,e:Date;if(preset.value==='month'){s=new Date(y,m,1);e=new Date(y,m+1,0)}else if(preset.value==='lastmonth'){s=new Date(y,m-1,1);e=new Date(y,m,0)}else if(preset.value==='quarter'){const q=Math.floor(m/3)*3;s=new Date(y,q,1);e=new Date(y,q+3,0)}else if(preset.value==='lastfy'){const fy=m>=6?y:y-1;s=new Date(fy-1,6,1);e=new Date(fy,5,30)}else if(preset.value==='custom')return;else{const fy=m>=6?y:y-1;s=new Date(fy,6,1);e=new Date(fy+1,5,30)}start.value=iso(s);end.value=iso(e);load()}
async function load(){err.value='';try{if(!isSuperAdmin.value)return navigateTo('/admin');data.value=await adminFetch(`/api/admin/accounting/analytics/profitability?start=${start.value}&end=${end.value}`)}catch(e:any){err.value=e?.data?.statusMessage||e.message||'Unable to load profitability analytics.'}}
const activeRows=computed(()=>tab.value==='products'?data.value.products||[]:tab.value==='categories'?data.value.categories||[]:data.value.customers||[]); const firstHeader=computed(()=>tab.value==='products'?'Product':tab.value==='categories'?'Category':'Customer'); const rowName=(x:any)=>tab.value==='categories'?x.category:x.name; const lowMargins=computed(()=>[...(data.value.margin_alerts||[])].slice(0,12)); const chartMax=computed(()=>Math.max(1,...(data.value.monthly||[]).flatMap((x:any)=>[num(x.revenue_ex_gst),Math.max(0,num(x.profit))]))); const bar=(v:any)=>`${Math.max(2,Math.round(Math.max(0,num(v))/chartMax.value*100))}%`; const month=(v:string)=>new Date(`${v}-01T00:00:00`).toLocaleDateString('en-AU',{month:'short'});
function exportCsv(){const rows=data.value.products||[];const esc=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[['Product','SKU','Category','Quantity','Orders','Sales ex GST','COGS','Gross Profit','Margin %'],...rows.map((x:any)=>[x.name,x.sku,x.category,x.quantity,x.orders,x.revenue_ex_gst,x.cogs,x.profit,x.margin_pct])].map(r=>r.map(esc).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`profitability-${start.value}-to-${end.value}.csv`;a.click();URL.revokeObjectURL(a.href)}
onMounted(()=>{applyPreset()});
</script>
<style scoped>.panel{@apply rounded-xl border border-slate-200 bg-white shadow-sm}.metric{@apply flex min-h-28 flex-col rounded-xl border border-slate-200 bg-white p-4 shadow-sm}.metric small{@apply text-xs font-black uppercase tracking-wide text-slate-500}.metric b{@apply mt-2 text-xl font-black}.field{@apply flex min-w-40 flex-col gap-1 text-xs font-bold text-slate-600}.field input,.field select{@apply rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900}.btn-primary{@apply rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white}.btn-secondary{@apply rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-bold}.tab{@apply rounded-lg border border-slate-200 bg-slate-50 px-4 py-2 text-sm font-bold}.tab.active{@apply border-blue-600 bg-blue-600 text-white}.box{@apply rounded-xl border border-slate-200 p-4}.box h2{@apply text-lg font-black}</style>
