<template>
  <main class="mx-auto max-w-[1500px] px-4 py-6 md:px-7 md:py-7">
    <AdminPurchasingWorkflow />
    <NuxtLink to="/admin/accounting/purchases" class="text-sm font-bold text-blue-600">← Purchase Orders</NuxtLink>
    <div class="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-3xl font-black">Receive Stock</h1><p class="text-slate-500">Receive outstanding stock from ordered purchase orders. Partial deliveries are supported.</p></div><button class="secondary" @click="load">Refresh</button></div>
    <div v-if="msg" class="my-4 rounded-lg bg-slate-100 p-3">{{ msg }}</div>
    <section class="panel mt-5 p-5"><h2 class="text-xl font-black">Purchase Orders Awaiting Stock</h2><div class="mt-3 overflow-x-auto"><table class="w-full min-w-[850px] text-sm"><thead><tr class="border-b text-left"><th class="p-2">PO</th><th>Supplier</th><th>Ordered</th><th>Expected</th><th>Status</th><th>Lines Outstanding</th><th></th></tr></thead><tbody><tr v-for="x in receivable" :key="x.id" class="border-b"><td class="p-2 font-bold">{{x.po_number}}</td><td>{{x.accounting_suppliers?.name}}</td><td>{{x.order_date}}</td><td>{{x.expected_date||'—'}}</td><td><span class="badge">{{x.status}}</span></td><td>{{ outstandingLines(x) }}</td><td class="text-right"><button class="primary" @click="openReceive(x)">Receive Stock</button></td></tr><tr v-if="!receivable.length"><td colspan="7" class="p-8 text-center text-slate-500">No purchase orders are waiting for stock.</td></tr></tbody></table></div></section>
    <section class="panel mt-5 p-5"><h2 class="text-xl font-black">Completed / Fully Received</h2><div class="mt-3 overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b text-left"><th class="p-2">PO</th><th>Supplier</th><th>Date</th><th>Status</th><th class="text-right">Total</th></tr></thead><tbody><tr v-for="x in completed" :key="x.id" class="border-b"><td class="p-2 font-bold">{{x.po_number}}</td><td>{{x.accounting_suppliers?.name}}</td><td>{{x.order_date}}</td><td>{{x.status}}</td><td class="text-right">{{money(x.total)}}</td></tr></tbody></table></div></section>
    <div v-if="receiving" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" @click.self="receiving=null"><div class="w-full max-w-3xl rounded-2xl bg-white p-6 shadow-2xl"><div class="flex items-start justify-between gap-3"><div><h2 class="text-xl font-black">Receive Stock — {{receiving.po_number}}</h2><p class="text-sm text-slate-500">{{receiving.accounting_suppliers?.name}}</p></div><button class="secondary" @click="receiving=null">Close</button></div><div class="mt-4 grid gap-3 md:grid-cols-2"><input v-model="receipt.received_date" type="date" class="input"><input v-model="receipt.supplier_reference" class="input" placeholder="Delivery docket / supplier reference"></div><div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b text-left"><th class="p-2">Product</th><th>Ordered</th><th>Received</th><th>Remaining</th><th class="w-28">Receive now</th></tr></thead><tbody><tr v-for="l in receiving.accounting_purchase_order_lines" :key="l.id" class="border-b"><td class="p-2"><b>{{l.description}}</b><div class="text-xs text-slate-500">{{l.sku||''}}</div></td><td>{{l.quantity}}</td><td>{{l.received_quantity||0}}</td><td>{{l.remaining_quantity||0}}</td><td><input v-if="l.product_id && Number(l.remaining_quantity)>0" v-model.number="receiptQty[l.id]" type="number" min="0" :max="l.remaining_quantity" step="1" class="input"><span v-else class="text-xs text-slate-400">{{l.product_id?'Complete':'Non-stock'}}</span></td></tr></tbody></table></div><textarea v-model="receipt.notes" class="input mt-3" rows="2" placeholder="Receiving notes (optional)"></textarea><div class="mt-4 flex justify-end"><button class="primary" @click="receiveStock">Receive Stock</button></div></div></div>
  </main>
</template>
<script setup lang="ts">
definePageMeta({layout:'admin',middleware:['admin']}); const {adminFetch}=useAdminFetch(); const pos=ref<any[]>([]),msg=ref(''),receiving=ref<any>(null); const receiptQty=reactive<Record<number,number>>({}); const receipt=reactive<any>({received_date:new Date().toISOString().slice(0,10),supplier_reference:'',notes:''});
const money=(v:any)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v||0)); const canReceive=(x:any)=>['sent','ordered','part_received'].includes(String(x?.status||'').toLowerCase()); const hasReceivable=(x:any)=>(x.accounting_purchase_order_lines||[]).some((l:any)=>l.product_id&&Number(l.remaining_quantity||0)>0); const receivable=computed(()=>pos.value.filter(x=>canReceive(x)&&hasReceivable(x))); const completed=computed(()=>pos.value.filter(x=>['received','billed'].includes(String(x.status||'').toLowerCase())&&!hasReceivable(x))); const outstandingLines=(x:any)=>(x.accounting_purchase_order_lines||[]).filter((l:any)=>l.product_id&&Number(l.remaining_quantity||0)>0).length;
async function load(){try{pos.value=await adminFetch('/api/admin/accounting/purchase-orders')||[]}catch(e:any){msg.value=e?.data?.statusMessage||e.message}} function openReceive(x:any){receiving.value=x;for(const k of Object.keys(receiptQty))delete receiptQty[Number(k)];for(const l of x.accounting_purchase_order_lines||[])if(l.product_id&&Number(l.remaining_quantity)>0)receiptQty[l.id]=Number(l.remaining_quantity);receipt.received_date=new Date().toISOString().slice(0,10);receipt.supplier_reference=x.supplier_reference||'';receipt.notes=''} async function receiveStock(){if(!receiving.value)return;try{await adminFetch(`/api/admin/accounting/purchase-orders/${receiving.value.id}/receive`,{method:'POST',body:{...receipt,lines:(receiving.value.accounting_purchase_order_lines||[]).map((l:any)=>({purchase_order_line_id:l.id,quantity:Number(receiptQty[l.id]||0)}))}});msg.value='Stock received and inventory updated.';receiving.value=null;await load()}catch(e:any){msg.value=e?.data?.statusMessage||e.message}} onMounted(load);
</script>
<style scoped>.panel{border:1px solid #e2e8f0;border-radius:1rem;background:white}.input{width:100%;border:1px solid #cbd5e1;border-radius:.7rem;padding:.65rem .75rem}.primary,.secondary{border-radius:.7rem;padding:.65rem 1rem;font-weight:800}.primary{background:#0f172a;color:white}.secondary{border:1px solid #cbd5e1;background:white}.badge{border-radius:999px;background:#f1f5f9;padding:.25rem .6rem;font-weight:700}</style>
