import {getAdminSupabase} from "~~/server/utils/adminAuth";import {createPostedJournal} from "~~/server/utils/accounting";
const r=(v:any)=>Math.round(Number(v||0)*100)/100;
async function acc(key:string){const{data,error}=await getAdminSupabase().from("accounting_accounts").select("id").eq("system_key",key).single();if(error||!data)throw new Error(`Accounting account '${key}' is missing.`);return Number(data.id)}
export function purchaseTotals(lines:any[]){let subtotal=0,gst=0;for(const x of lines||[]){const ex=r(Number(x.quantity||0)*Number(x.unit_cost_ex_gst||0));subtotal=r(subtotal+ex);gst=r(gst+r(ex*.1))}return{subtotal,gst_amount:gst,total:r(subtotal+gst)}}
export async function postSupplierBill(billId:number,userId?:string){const s=getAdminSupabase();const{data:b,error}=await s.from("accounting_supplier_bills").select("*,accounting_supplier_bill_lines(*)").eq("id",billId).single();if(error||!b)throw error||new Error("Supplier bill not found");if(b.journal_id)return b;const payable=await acc("accounts_payable"),gstPaid=await acc("gst_paid"),inventory=await acc("inventory"),expense=await acc("general_expense");const lines:any[]=[];for(const x of b.accounting_supplier_bill_lines||[]){lines.push({account_id:Number(x.account_id|| (x.product_id?inventory:expense)),debit:r(Number(x.quantity)*Number(x.unit_cost_ex_gst)),credit:0,description:x.description})}if(Number(b.gst_amount)>0)lines.push({account_id:gstPaid,debit:Number(b.gst_amount),credit:0,description:"GST paid / receivable"});lines.push({account_id:payable,debit:0,credit:Number(b.total),description:`Accounts payable — ${b.bill_number}`});const j=await createPostedJournal({journal_date:b.bill_date,reference:b.supplier_invoice_number||b.bill_number,description:`Supplier bill ${b.bill_number}`,source_type:"supplier_bill",source_id:String(b.id),posted_by:userId,lines});const{data:updated,error:ue}=await s.from("accounting_supplier_bills").update({status:"unpaid",journal_id:j.id,updated_at:new Date().toISOString()}).eq("id",b.id).select().single();if(ue)throw ue;return updated}
export async function paySupplierBill(billId:number,amount:number,reference:string,userId?:string){const s=getAdminSupabase();const{data:b,error}=await s.from("accounting_supplier_bills").select("*").eq("id",billId).single();if(error||!b)throw error||new Error("Bill not found");const remaining=r(Number(b.total)-Number(b.paid_amount));amount=r(amount);if(amount<=0||amount>remaining)throw new Error("Payment must be greater than zero and cannot exceed the outstanding balance.");const payable=await acc("accounts_payable"),bank=await acc("bank");const j=await createPostedJournal({journal_date:new Date().toISOString().slice(0,10),reference,description:`Payment of ${b.bill_number}`,source_type:"supplier_payment",source_id:String(b.id),posted_by:userId,lines:[{account_id:payable,debit:amount,credit:0,description:`Payment ${b.bill_number}`},{account_id:bank,debit:0,credit:amount,description:reference||`Payment ${b.bill_number}`}]});await s.from("accounting_supplier_payments").insert({bill_id:b.id,amount,reference:reference||null,journal_id:j.id});const paid=r(Number(b.paid_amount)+amount),status=paid>=Number(b.total)?"paid":"part_paid";const{data:u,error:ue}=await s.from("accounting_supplier_bills").update({paid_amount:paid,status,updated_at:new Date().toISOString()}).eq("id",b.id).select().single();if(ue)throw ue;return u}

export async function paySupplierBills(input:{supplierId:number;reference:string;paymentDate:string;allocations:Array<{bill_id:number;amount:number}>;userId?:string}){
  const s=getAdminSupabase();
  const supplierId=Number(input.supplierId);
  const allocations=(input.allocations||[]).map(x=>({bill_id:Number(x.bill_id),amount:r(x.amount)})).filter(x=>x.bill_id&&x.amount>0);
  if(!supplierId||!allocations.length)throw new Error("Select at least one supplier bill to pay.");
  const ids=[...new Set(allocations.map(x=>x.bill_id))];
  if(ids.length!==allocations.length)throw new Error("A supplier bill can only be allocated once per payment.");
  const{data:bills,error}=await s.from("accounting_supplier_bills").select("*").in("id",ids);
  if(error)throw error;
  if(!bills||bills.length!==ids.length)throw new Error("One or more supplier bills could not be found.");
  for(const b of bills){if(Number(b.supplier_id)!==supplierId)throw new Error("All bills in a supplier payment must belong to the same supplier.");const a=allocations.find(x=>x.bill_id===Number(b.id))!;const remaining=r(Number(b.total)-Number(b.paid_amount));if(a.amount<=0||a.amount>remaining)throw new Error(`Payment for ${b.bill_number} cannot exceed the outstanding balance.`)}
  const total=r(allocations.reduce((sum,x)=>sum+x.amount,0));
  const payable=await acc("accounts_payable"),bank=await acc("bank");
  const reference=String(input.reference||"");
  const paymentDate=/^\d{4}-\d{2}-\d{2}$/.test(input.paymentDate||"")?input.paymentDate:new Date().toISOString().slice(0,10);
  const billNumbers=bills.map(b=>b.bill_number).join(", ");
  const j=await createPostedJournal({journal_date:paymentDate,reference,description:`Supplier payment — ${billNumbers}`,source_type:"supplier_payment",source_id:`supplier:${supplierId}`,posted_by:input.userId,lines:[{account_id:payable,debit:total,credit:0,description:`Payment allocated to ${billNumbers}`},{account_id:bank,debit:0,credit:total,description:reference||`Supplier payment ${billNumbers}`}]});
  const paymentRows=allocations.map(x=>({bill_id:x.bill_id,amount:x.amount,reference:reference||null,journal_id:j.id}));
  const{error:pe}=await s.from("accounting_supplier_payments").insert(paymentRows);if(pe)throw pe;
  for(const b of bills){const a=allocations.find(x=>x.bill_id===Number(b.id))!;const paid=r(Number(b.paid_amount)+a.amount),status=paid>=Number(b.total)?"paid":"part_paid";const{error:ue}=await s.from("accounting_supplier_bills").update({paid_amount:paid,status,updated_at:new Date().toISOString()}).eq("id",b.id);if(ue)throw ue}
  return{ok:true,journal_id:j.id,total,allocated_bills:allocations.length};
}
