import { getAdminSupabase } from "~~/server/utils/adminAuth";
const n=(v:any)=>Number(v||0); const r=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;
export const csv=(rows:any[])=>{if(!rows.length)return "";const keys=[...new Set(rows.flatMap(x=>Object.keys(x)))];const q=(v:any)=>`"${String(v??"").replace(/"/g,'""')}"`;return [keys.map(q).join(','),...rows.map(x=>keys.map(k=>q(typeof x[k]==='object'?JSON.stringify(x[k]):x[k])).join(','))].join('\r\n')+'\r\n'};
export async function buildYearEndData(start:string,end:string){
 const s=getAdminSupabase();
 const [{data:accounts,error:ae},{data:lines,error:le},{data:allLines,error:ale},{data:products,error:proe},{data:invoices,error:ie},{data:bills,error:be},{data:moves,error:me},{data:bank,error:bke},{data:recs,error:re},{data:periods,error:pe}]=await Promise.all([
  s.from('accounting_accounts').select('*').order('code'),
  s.from('accounting_journal_lines').select('id,journal_id,account_id,description,debit,credit,accounting_accounts(id,code,name,account_type),accounting_journals!inner(id,journal_date,status,reference,description,source_type,source_id,created_at)').eq('accounting_journals.status','posted').gte('accounting_journals.journal_date',start).lte('accounting_journals.journal_date',end).order('id'),
  s.from('accounting_journal_lines').select('debit,credit,accounting_accounts(id,code,name,account_type),accounting_journals!inner(journal_date,status)').eq('accounting_journals.status','posted').lte('accounting_journals.journal_date',end),
  s.from('products').select('id,name,product_code,buy_price_ex_gst,price,stock,active').order('name'),
  s.from('accounting_invoices').select('*').lte('invoice_date',end).order('invoice_date'),
  s.from('accounting_supplier_bills').select('*,accounting_suppliers(name)').lte('bill_date',end).order('bill_date'),
  s.from('accounting_inventory_movements').select('id,product_id,order_id,movement_date,movement_type,quantity,unit_cost,total_cost,reference,notes,journal_id').gte('movement_date',start).lte('movement_date',end).order('movement_date'),
  s.from('accounting_bank_transactions').select('*').gte('transaction_date',start).lte('transaction_date',end).order('transaction_date'),
  s.from('accounting_bank_reconciliations').select('*').gte('statement_date',start).lte('statement_date',end).order('statement_date'),
  s.from('accounting_periods').select('*').gte('end_date',start).lte('start_date',end).order('start_date')
 ]);
 const err=[ae,le,ale,proe,ie,be,me,bke,re,pe].find(Boolean); if(err)throw createError({statusCode:500,statusMessage:(err as any).message});
 const generalLedger=(lines||[]).map((x:any)=>{const a=x.accounting_accounts||{},j=x.accounting_journals||{};return{date:j.journal_date,journal_id:j.id,reference:j.reference||'',journal_description:j.description||'',source_type:j.source_type||'',source_id:j.source_id||'',account_code:a.code||'',account_name:a.name||'',account_type:a.account_type||'',line_description:x.description||'',debit:n(x.debit),credit:n(x.credit)}});
 const tb=new Map<string,any>(); for(const x of generalLedger){const k=x.account_code;const v=tb.get(k)||{code:k,name:x.account_name,account_type:x.account_type,debit:0,credit:0};v.debit+=x.debit;v.credit+=x.credit;tb.set(k,v)}
 const trialBalance=[...tb.values()].map(x=>({...x,debit:r(x.debit),credit:r(x.credit),balance:r(x.debit-x.credit)})).sort((a,b)=>a.code.localeCompare(b.code));
 const pnlAccounts=new Map<string,any>(); for(const x of generalLedger){const t=String(x.account_type).toLowerCase(),income=['income','revenue'].includes(t),expense=['expense','cost_of_sales','cost of sales','cogs'].includes(t);if(!income&&!expense)continue;const cogs=expense&&(t.includes('cost')||t==='cogs'||x.account_code==='5000'||/cost of goods|cogs/i.test(x.account_name));const group=income?'Income':cogs?'COGS':'Operating Expenses';const v=pnlAccounts.get(x.account_code)||{code:x.account_code,name:x.account_name,group,amount:0};v.amount+=income?x.credit-x.debit:x.debit-x.credit;pnlAccounts.set(x.account_code,v)}
 const pnl=[...pnlAccounts.values()].map(x=>({...x,amount:r(x.amount)}));const income=r(pnl.filter(x=>x.group==='Income').reduce((a,x)=>a+x.amount,0)),cogs=r(pnl.filter(x=>x.group==='COGS').reduce((a,x)=>a+x.amount,0)),expenses=r(pnl.filter(x=>x.group==='Operating Expenses').reduce((a,x)=>a+x.amount,0));
 const bsMap=new Map<string,any>();let currentEarnings=0;for(const x of (allLines||[]) as any[]){const a:any=x.accounting_accounts||{};const t=String(a.account_type||'').toLowerCase(),debit=n(x.debit),credit=n(x.credit);if(['income','revenue'].includes(t))currentEarnings+=credit-debit;if(['expense','cost_of_sales','cost of sales','cogs'].includes(t))currentEarnings-=debit-credit;if(!['asset','liability','equity'].includes(t))continue;const k=String(a.id);const v=bsMap.get(k)||{code:a.code,name:a.name,account_type:t,debit:0,credit:0};v.debit+=debit;v.credit+=credit;bsMap.set(k,v)}const balanceSheet=[...bsMap.values()].map(x=>({...x,balance:r(x.account_type==='asset'?x.debit-x.credit:x.credit-x.debit)})).sort((a,b)=>String(a.code).localeCompare(String(b.code)));
 const inventoryValuation=(products||[]).map((p:any)=>({product_id:p.id,sku:p.product_code||'',name:p.name,stock:n(p.stock),unit_cost_ex_gst:r(n(p.buy_price_ex_gst)),inventory_value_ex_gst:r(n(p.stock)*n(p.buy_price_ex_gst)),retail_value:r(n(p.stock)*n(p.price)),active:p.active!==false}));
 const ar=(invoices||[]).map((x:any)=>({...x,balance:r(n(x.total)-n(x.paid_amount))})).filter((x:any)=>x.balance>0.005);
 const ap=(bills||[]).map((x:any)=>({...x,supplier_name:x.accounting_suppliers?.name||'',balance:r(n(x.total)-n(x.paid_amount)),accounting_suppliers:undefined})).filter((x:any)=>x.balance>0.005);
 const health={unbalanced_journals:trialBalance.length?Math.abs(trialBalance.reduce((a,x)=>a+x.debit,0)-trialBalance.reduce((a,x)=>a+x.credit,0))>0.005:false,unreconciled_bank_transactions:(bank||[]).filter((x:any)=>String(x.status).toLowerCase()!=='reconciled').length,negative_or_invalid_invoice_balances:(invoices||[]).filter((x:any)=>n(x.paid_amount)<0||n(x.paid_amount)>n(x.total)+.005).length,negative_or_invalid_bill_balances:(bills||[]).filter((x:any)=>n(x.paid_amount)<0||n(x.paid_amount)>n(x.total)+.005).length};
 return{period:{start,end},generated_at:new Date().toISOString(),summary:{income,cogs,gross_profit:r(income-cogs),operating_expenses:expenses,net_profit:r(income-cogs-expenses),accounts_receivable:r(ar.reduce((a,x)=>a+x.balance,0)),accounts_payable:r(ap.reduce((a,x)=>a+x.balance,0)),journal_debits:r(generalLedger.reduce((a,x)=>a+x.debit,0)),journal_credits:r(generalLedger.reduce((a,x)=>a+x.credit,0)),inventory_value_ex_gst:r(inventoryValuation.reduce((a,x)=>a+x.inventory_value_ex_gst,0)),current_earnings:r(currentEarnings)},accounts:accounts||[],trialBalance,generalLedger,profitLoss:pnl,balanceSheet,inventoryValuation,accountsReceivable:ar,accountsPayable:ap,inventoryMovements:moves||[],bankTransactions:bank||[],bankReconciliations:recs||[],periods:periods||[],health};
}
