import { COMPANY_LOGO_HEIGHT, COMPANY_LOGO_JPEG_BASE64, COMPANY_LOGO_WIDTH } from "./invoicePdf";

type Line={sku?:string|null;description?:string|null;quantity?:number|null;unit_cost_ex_gst?:number|null};
export type PurchaseOrderPdfData={id:number|string;po_number?:string|null;order_date?:string|null;expected_date?:string|null;supplier_reference?:string|null;notes?:string|null;subtotal?:number|null;gst_amount?:number|null;total?:number|null;freight_estimated_ex_gst?:number|null;freight_actual_ex_gst?:number|null;accounting_suppliers?:any;accounting_purchase_order_lines?:Line[]};
const safe=(v:any)=>String(v??"").normalize("NFKD").replace(/[^\x20-\x7E]/g,"?").replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");
const money=(v:any)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v||0));
const date=(v:any)=>{if(!v)return"";const d=new Date(String(v).slice(0,10)+"T00:00:00");return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("en-AU",{day:"2-digit",month:"short",year:"numeric"}).format(d)};
const wrap=(v:any,n=72)=>{const w=String(v??"").split(/\s+/).filter(Boolean),out:string[]=[];let c="";for(const x of w){const z=c?`${c} ${x}`:x;if(z.length<=n)c=z;else{if(c)out.push(c);c=x}}if(c)out.push(c);return out.length?out:[""]};
export function createPurchaseOrderPdf(po:PurchaseOrderPdfData){
 const W=595,H=842,L=46,R=549,TOP=795,BOT=50,sup=po.accounting_suppliers||{},lines=po.accounting_purchase_order_lines||[];let y=TOP;const pages:string[][]=[[]];let pi=0;const p=()=>pages[pi],cmd=(x:string)=>p().push(x),font=(b=false,s=9)=>cmd(`/${b?'F2':'F1'} ${s} Tf`),text=(x:number,yy:number,v:any)=>cmd(`BT 1 0 0 1 ${x} ${yy} Tm (${safe(v)}) Tj ET`),line=(x1:number,y1:number,x2:number,y2:number)=>cmd(`${x1} ${y1} m ${x2} ${y2} l S`),logo=()=>cmd(`q 72 0 0 72 ${L} ${y-65} cm /Im1 Do Q`);
 const header=(cont=false)=>{logo();font(true,20);text(L+86,y-20,"KIALLA COMPUTERS");font(false,10);text(L+86,y-38,cont?"PURCHASE ORDER - CONTINUED":"PURCHASE ORDER");font(true,12);text(395,y-8,po.po_number||`PO-${po.id}`);font(false,8);text(395,y-24,`Order: ${date(po.order_date)}`);if(po.expected_date)text(395,y-38,`Expected: ${date(po.expected_date)}`);y-=84;line(L,y,R,y);y-=18};
 const ensure=(n:number)=>{if(y-n>=BOT)return;pi++;pages.push([]);y=TOP;header(true)};header();font(true,9);text(L,y,"SUPPLIER");font(false,9);y-=15;text(L,y,sup.name||"Supplier");if(sup.contact_name){y-=12;text(L,y,`Attn: ${sup.contact_name}`)}if(sup.address)for(const a of wrap(sup.address,58)){y-=12;text(L,y,a)}if(sup.email){y-=12;text(L,y,sup.email)}if(sup.phone){y-=12;text(L,y,sup.phone)};let ry=y+60;font(true,9);text(340,ry,"ORDER DETAILS");font(false,9);ry-=15;text(340,ry,`Supplier ref: ${po.supplier_reference||'-'}`);ry-=13;text(340,ry,"Currency: AUD");ry-=13;text(340,ry,"Prices: Ex GST");y=Math.min(y,ry)-22;
 ensure(50);font(true,8);text(L,y,"SKU");text(120,y,"DESCRIPTION");text(405,y,"QTY");text(455,y,"UNIT EX");text(520,y,"LINE EX");y-=8;line(L,y,R,y);y-=14;font(false,8);
 for(const l of lines){const desc=wrap(l.description||"Item",42);ensure(18+desc.length*10);text(L,y,l.sku||"-");text(405,y,Number(l.quantity||0));text(455,y,money(l.unit_cost_ex_gst));text(520,y,money(Number(l.quantity||0)*Number(l.unit_cost_ex_gst||0)));for(let i=0;i<desc.length;i++)text(120,y-i*10,desc[i]);y-=Math.max(18,desc.length*10+7);line(L,y+6,R,y+6)}
 ensure(100);y-=8;font(false,9);text(410,y,"Products ex GST");font(true,9);text(505,y,money(Number(po.subtotal||0)-Number(po.freight_estimated_ex_gst||0)));y-=15;font(false,9);text(410,y,"Freight ex GST");font(true,9);text(505,y,money(po.freight_estimated_ex_gst));y-=15;font(false,9);text(410,y,"GST");font(true,9);text(505,y,money(po.gst_amount));y-=18;line(405,y+8,R,y+8);font(true,11);text(410,y,"TOTAL AUD");text(500,y,money(po.total));y-=28;
 if(po.notes){ensure(70);font(true,9);text(L,y,"NOTES");y-=14;font(false,8);for(const n of wrap(po.notes,95)){ensure(12);text(L,y,n);y-=11}}
 ensure(35);y-=10;line(L,y,R,y);y-=14;font(false,8);text(L,y,"Kialla Computers | Purchase Order");text(410,y,po.po_number||`PO-${po.id}`);
 const objs:Array<Buffer|undefined>=[];const pageNums:number[]=[],contentNums:number[]=[];let next=6;for(let i=0;i<pages.length;i++){pageNums.push(next++);contentNums.push(next++)}objs[1]=Buffer.from("<< /Type /Catalog /Pages 2 0 R >>","latin1");objs[2]=Buffer.from(`<< /Type /Pages /Kids [${pageNums.map(n=>`${n} 0 R`).join(" ")}] /Count ${pages.length} >>`,"latin1");objs[3]=Buffer.from("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>","latin1");objs[4]=Buffer.from("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>","latin1");const lb=Buffer.from(COMPANY_LOGO_JPEG_BASE64,"base64");objs[5]=Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${COMPANY_LOGO_WIDTH} /Height ${COMPANY_LOGO_HEIGHT} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${lb.length} >>\nstream\n`,`latin1`),lb,Buffer.from("\nendstream","latin1")]);for(let i=0;i<pages.length;i++){const st=Buffer.from(pages[i].join("\n"),"latin1");objs[pageNums[i]]=Buffer.from(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> /XObject << /Im1 5 0 R >> >> /Contents ${contentNums[i]} 0 R >>`,`latin1`);objs[contentNums[i]]=Buffer.concat([Buffer.from(`<< /Length ${st.length} >>\nstream\n`,`latin1`),st,Buffer.from("\nendstream","latin1")])}const chunks:Buffer[]=[Buffer.from("%PDF-1.4\n%\xE2\xE3\xCF\xD3\n","latin1")],offs:number[]=[0];let len=chunks[0].length;for(let i=1;i<objs.length;i++){const b=objs[i];if(!b)throw new Error(`Missing PDF object ${i}`);offs[i]=len;const a=Buffer.from(`${i} 0 obj\n`,`latin1`),z=Buffer.from("\nendobj\n","latin1");chunks.push(a,b,z);len+=a.length+b.length+z.length}const xo=len;let xr=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)xr+=`${String(offs[i]).padStart(10,"0")} 00000 n \n`;xr+=`trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xo}\n%%EOF\n`;chunks.push(Buffer.from(xr,"latin1"));return Buffer.concat(chunks)
}
export const getPurchaseOrderFilename=(po:PurchaseOrderPdfData)=>`${po.po_number||`PO-${po.id}`}.pdf`;
